nextcloud-snap/nextcloud-snap

parts/plugins/x-apache.py, snapcraft.yaml, src/nextcloud/apache_config, src/nextcloud/autoconfig.php, src/nextcloud/occ, src/nextcloud/setup_nextcloud, src/php/config/php-fpm.conf, src/php/config/php-fpm.d/www.conf, src/php/config/php.ini, src/php/scripts/start-php-fpm
This PR resolves #3 by using PHP FPM instead of the PHP apache module. It uses pm=ondemand and determines max children by total RAM.
=> Use PHP FPM instead of PHP Apache module.

CHANGELOG, README.md, parts/plugins/x-apache.py, parts/plugins/x-php.py, snapcraft.yaml, src/nextcloud/setup_nextcloud
Also update to pull PHP extensions in the pull step to be compatible with the Launchpad snap builders. Finally, make sure Redis is used even if the installation isn't new.
=> Update version to 9.0.50snap2.

snapcraft.yaml, src/php/scripts/start-php-fpm
This PR fixes #11 by bundling mawk into the snap rather than relying on the one in core. Otherwise LP: #1580018 allows the host system to mess with the awk found by snaps. When that bug is fixed this PR can be reverted.
=> Bundle mawk.

src/nextcloud/setup_nextcloud
This PR fixes #10 by waiting for PHP to be up before attempting to use the `occ` command.
=> Wait for PHP to be up before trying to use occ.

snapcraft.yaml
This PR fixes #24 by building PHP with jpeg support, which means Nextcloud can now generate thumbnails and previews. Please test with the following:
```bash
$ sudo snap install nextcloud --edge
```
Upload .jpg and .png images, and verify that thumbnails are generated. Also verify that, when selecting them, previews are successfully shown.
=> Build PHP with jpeg support.

src/apache/conf/httpd.conf, src/php/config/php.ini
Image verification noted a failure to upload 1.5GB file on rpi2, logs indicated a timeout occurred.
=> Increase PHP and Apache proxy timeout to 3600 seconds.

snapcraft.yaml, src/nextcloud/scripts/nextcloud-cron
Fixes #39 
A second attempt based on #42 
I changed the name of the service to nextcloud-cron as suggested, and moved the script into src/nextcloud/scripts/nextcloud-cron as that seemed to make more sense.
When building, I needed to do:
snapcraft clean
snapcraft
So that the wildcard in nextcloud-customizations picked up the new nextcloud-cron script...
=> Add service that runs cron.php every 15 minutes

snapcraft.yaml, src/nextcloud/config/config.php, src/php/config/php.ini
This PR resolves #40 by upgrading to Nextcloud 10.0.1, which means we can finally use vanilla upstream and enable the integrity check!
Test it out on amd64 with [this snap](http://people.canonical.com/~kyrofa/nextcloud-box/pr_76.snap).
=> Upgrade to Nextcloud 10.

src/https/scripts/enable-https
This PR fixes #74 by improving the message when a dry-run succeeds. It also no longer unnecessarily restarts Apache.
Test this PR out on amd64 with [this snap](http://people.canonical.com/~kyrofa/nextcloud-box/pr_75.snap).
=> https: show better message when a dry-run succeeds.

src/apache/scripts/httpd-wrapper, src/apache/scripts/run-httpd
Currently the code that takes care of migrating old certificates actually gets in the way of generating new certificates by causing Apache to get restarted in a loop. This PR fixes #103 by moving that migration code up a level so it isn't involved when restarting Apache.
=> Move certificate migration to run-httpd.

.travis/cron.sh
Fix #137 by using `latest-master` and `latest-stable10` for daily build versions.
=> Daily builds: use versions that indicate so.

snapcraft.yaml
This PR fixes #32 by removing the updater app from the snap completely. This does not result in an integrity check failure.
=> Nextcloud: remove updater app.

snapcraft.yaml, src/php/config/php.ini
Reverts #155 as PHP 7.1 doesn't seem to build on arm64.
=> Revert "Update PHP to 7.1"

src/https/certbot_nextcloud_plugin/webroot.py, src/https/setup.py
Currently the certbot plugin used in the snap is a copy of the webroot plugin from upstream certbot with the chown bits commented out. However, it turns out that the webroot plugin as-written cannot be used as an external plugin. It's far more complicated than we needed anyway, so this PR fixes #159 by rewriting it to be exactly what we need.
=> https: rewrite certbot plugin.

.travis/cron.sh
Fix #166 by only matching the snap version and not every "version" string.
=> dailies: fix overly-fragile version regex.

src/apache/conf/httpd.conf, src/apache/conf/ssl.conf
Make the alias for acme-challenge less greedy.
Include the rewrites from htaccess in the correct directory
Fix #111
=> Allow standard .well-known paths to work

snapcraft.yaml, src/apache/conf/httpd.conf, src/apache/scripts/httpd-wrapper, src/apache/utilities/apache-utilities, src/https/utilities/https-utilities, src/mysql/mysql.server, src/mysql/start_mysql, src/mysql/utilities/mysql-utilities, src/nextcloud/config/autoconfig.php, src/nextcloud/config/config.php, src/nextcloud/scripts/nextcloud-cron, src/nextcloud/scripts/occ, src/nextcloud/scripts/setup_nextcloud, src/nextcloud/utilities/nextcloud-utilities, src/php/config/php-fpm.conf, src/php/config/php-fpm.d/www.conf, src/php/scripts/start-php-fpm, src/php/utilities/php-utilities, src/redis/config/redis.conf, src/redis/scripts/start-redis-server, src/redis/utilities/redis-utilities
This PR fixes #151 by placing all pidfiles and sockets in /tmp.
Until recently, /tmp within a snap was unique to the app in the snap. This meant that any sockets or pidfiles placed into /tmp in app A was not accessible from app B (as it saw a separate /tmp).
As of snap-confine v1.0.43, this is no longer the case. /tmp is now unique snap-wide: /tmp for app A is the same /tmp as app B as long as both apps are contained within the same snap.
This finally gives us a place accessible from confinement that's wiped on each boot. It's the place to put pidfiles and sockets so hard reboots don't cause future failures.
=> many: place all pidfiles and sockets in /tmp.

README.md, snap/snapcraft.yaml, src/mysql/start_mysql, src/mysql/utilities/mysql-utilities, src/nextcloud/config/autoconfig.php, src/nextcloud/scripts/manual-install, src/nextcloud/scripts/occ, src/nextcloud/utilities/nextcloud-utilities, src/php/scripts/start-php-fpm
This PR resolves #208 by adding a `manual-install` command that allows for the admin user to be created from the CLI instead of requiring one to use their browser.
=> Add new command for manually installing.

src/nextcloud/scripts/setup_nextcloud
This PR finishes off the fix to #151 by making sure that configs from old revisions of the snap are migrated to use the new sockets location.
=> nextcloud: migrate old config to new use sockets.

snap/snapcraft.yaml
This PR resolves #224 by pulling boost from GitHub as opposed to Sourceforge, which is far too slow.
=> boost: pull from github instead of sourceforge.

src/mysql/start_mysql, src/nextcloud/scripts/setup_nextcloud
In v11.0.2snap1, the location of the sockets in the snap changed to be in `/tmp`. However, it neglected to migrate the socket path specified in MySQL's `root.ini`, which is used by the MySQL client.
This PR fixes #228 by fixing that path.
=> mysql: fix socket location in root.ini.

.travis/cron.sh
This PR fixes #239 by making daily builds use `snap/snapcraft.yaml`. Without this, daily builds are unable to modify the YAML and end up just being normal releases.
=> CI: make daily builds use snap/snapcraft.yaml

src/apache/conf/httpd.conf, src/apache/conf/ssl.conf
TRACE and TRACK are HTTP debugging methods, and it has been shown that they can be used for cross-site-scripting attacks. These methods are not necessary for a properly-functioning Nextcloud install, so this PR resolves #250 by disabling them.
=> apache: disable HTTP methods TRACE and TRACK

.travis/cron.sh
This PR fixes #255 by no longer verifying the checksum for the daily Nextcloud tarballs.
=> Don't verify checksum for daily builds.

src/apache/conf/ssl.conf
This PR resolves #258 by disabling 3DES SSL algorithms, which were reported by both Nessus and SSL Labs to be weak.
=> Remove weak 3DES SSL algorithms

snap/snapcraft.yaml
This PR resolves #267 by upgrading Redis to v3.2.8.
=> redis: upgrade to 3.2.8

snap/snapcraft.yaml, src/php/config/php.ini
This tries to fix https://github.com/nextcloud/nextcloud-snap/issues/60.
I added libsmbclient from the repos and php-libsmb as a php extension, but when trying to create the snap I get this error:
```
Parts 'certbot-nextcloud-plugin' and 'php' have the following file paths in common which have different contents:
6/5/17 10:046/5/17 10:04usr/bin/2to3-2.7
usr/bin/pydoc2.7
usr/lib/python2.7/UserString.py
usr/lib/python2.7/base64.py
usr/lib/python2.7/cProfile.py
usr/lib/python2.7/cgi.py
usr/lib/python2.7/encodings/rot_13.py
usr/lib/python2.7/ensurepip/__init__.py
usr/lib/python2.7/keyword.py
usr/lib/python2.7/lib2to3/pgen2/token.py
usr/lib/python2.7/mimify.py
usr/lib/python2.7/pdb.py
usr/lib/python2.7/platform.py
usr/lib/python2.7/profile.py
usr/lib/python2.7/pydoc.py …
```
=> Add samba client support

README.md, snap/snapcraft.yaml, src/apache/conf/httpd.conf, src/apache/conf/ssl.conf, src/apache/scripts/httpd-wrapper, src/apache/utilities/apache-utilities, src/hooks/configure
Currently, Apache listens on port 80. If HTTPS is enabled, it listens on both 80 and 443. This is inflexible, especially if one wants to put the snap behind a proxy of some kind.
This PR fixes #134 by adding support for changing HTTP and HTTPS ports via the `configure` hook. It exposes these configurations via the `ports.http` and `ports.https` options, respectively.
To test this, please install one of the following snaps via `sudo snap install --dangerous <snap>` and follow the documentation added in this PR to the README:
- [amd64](https://code.launchpad.net/~kyrofa/+snap/nextcloud-test/+build/37279/+files/nextcloud_11.0.3snap1_amd64.snap)
- [i386](https://code.launchpad.net/~kyrofa/+snap/nextcloud-test/+build/37282/+files/nextcloud_11.0.3snap1_i386.snap)
- …
=> apache: support changing ports

snap/snapcraft.yaml, src/php/config/php.ini
Fixes #60 by adding libsmbclient-php and libsmbclient. **Note:** We had to install libsmbclient from the python plugin, as it's python dependency conflicted with the python pulled by the certbot part when directly staged. See LP: [#1630996](https://bugs.launchpad.net/snapcraft/+bug/1630996) for more information.
=> Add samba client support.

snap/snapcraft.yaml, src/php/config/php.ini
This PR re-breaks #60 by reverting commit 9acd46f314cc036bd06aa8a74365ef847cd6623b (PR #271). It doesn't work on armhf (and potentially other architectures), and seems to also break webdav on armhf.
@pachulo, please feel free to debug this further and re-propose if you manage to figure out what's going on.
=> Revert "Add samba client support."

src/https/setup.py
The recent release of configargparse broke certbot, which made getting Let's Encrypt certificates in the snap impossible. Certbot fixed it in a later version, so this PR fixes #279 by updating the version of certbot used in the snap to the latest (v0.14.1).
To test this PR, run:
```
$ sudo snap install nextcloud --channel=stable/pr-284-certbot-update
```
If you already have the snap installed, run:
```
$ sudo snap refresh nextcloud --channel=stable/pr-284-certbot-update
```
Once this PR is contained in a release, I'll close that channel and you'll be back on the `stable` channel. So you're welcome to continue using it out of that branch to get unblocked.
=> certbot: update to 0.14.1

snap/snapcraft.yaml
This PR resolves #94 by updating MySQL to the latest 5.7.18 release.
In order to test this PR, run:
```
$ sudo snap install nextcloud --channel=stable/pr-283
```
We need to make sure we test upgrades particularly well (e.g. install the snap from stable, upload some files, add users, add contacts/calendars, etc. Then `sudo snap refresh nextcloud --channel=stable/pr-283`). The snap has code to run the mysql upgrade commands, but this will be our first actual mysql upgrade, so it hasn't gotten much (any) exercise.
=> mysql: update to 5.7.18

snap/snapcraft.yaml
This PR resolves #290 by updating PHP from 7.0.18, which has multiple security vulnerabilities, to 7.0.19.
Please test this PR with:
$ sudo snap install --channel=stable/pr-291 nextcloud
=> php: update to 7.0.19

.circleci/config.yml, snap/snapcraft.yaml, src/apache/conf/httpd.conf
This PR resolves #311 by updating Apache from 2.4.25 to 2.4.26.
Please test this PR by installing the snap from the `stable/pr-312` branch:
$ sudo snap install nextcloud --channel=stable/pr-312
$ sudo snap refresh nextcloud --channel=stable/pr-312
=> apache: update to 2.4.26

.gitignore, snap/snapcraft.yaml
This PR resolves #317 by using the godeps `dependencies.tsv` file contained within mdns-publisher to manage its dependencies.
=> mdns-publisher: use godeps to manage dependencies

snap/snapcraft.yaml
This PR resolves #319 by updating Apache to v2.4.27. Is also changes the checksum to use sha256 instead of SHA1.
To test this PR, install from the `stable/pr-320` channel:
$ sudo snap install nextcloud --channel=stable/pr-320
If you already have it installed:
$ sudo snap refresh nextcloud --channel=stable/pr-320
=> apache: update to 2.4.27

snap/snapcraft.yaml
This PR resolves #321 by updating PHP to 7.0.21.
Please test this PR by installing from the `stable/pr-323` channel:
$ sudo snap install nextcloud --channel=stable/pr-323
$ sudo snap refresh nextcloud --channel=stable/pr-323
=> php: update to 7.0.21

snap/snapcraft.yaml
Nextcloud v12 is pretty buggy. This PR resolves #335 by updating the snap to v11.0.4 while we're trying to stabilize. Please test this PR by using the `stable/pr-338` channel:
$ sudo snap install nextcloud --channel=stable/pr-338
$ sudo snap refresh nextcloud --channel=stable/pr-338
=> nextcloud: update to 11.0.4

snap/snapcraft.yaml
This PR resolves #339 by updating PHP to v7.0.22 (from v7.0.21).
Please test this PR by using the `stable/pr-340` channel:
$ sudo snap install nextcloud --channel=stable/pr-340
$ sudo snap refresh nextcloud --channel=stable/pr-340
=> php: update to 7.0.22

snap/snapcraft.yaml
This PR resolves #357 by updating Nextcloud to v11.0.5.
In order to test this, please use the `stable/pr-360` channel:
sudo snap install nextcloud --channel=stable/pr-360
If already installed:
sudo snap refresh nextcloud --channel=stable/pr-360
=> nextcloud: update to v11.0.5

snap/snapcraft.yaml
This PR fixes #361 by both updating Redis to 4.0.2 and using v3.1.4 of the PHP module.
To test this PR, use the `stable/pr-362` channel:
$ sudo snap install nextcloud --channel=stable/pr-362
$ sudo refresh nextcloud --channel=stable/pr-362
=> redis: update to 4.0.2

snap/plugins/x-php.py, snap/snapcraft.yaml
The tag somehow changed such that the version was `develop` instead of `3.1.4`. This PR 
fixes #370 by using the tarball and making sure it can't change without us noticing by verifying the checksum.
=> phpredis: use 3.1.4 tarball and checksum

snap/snapcraft.yaml
This PR fixes #372 by upgrading Apache from v2.4.27 to v2.4.28.
=> apache: update to 2.4.28

.circleci/config.yml, .circleci/runtests.sh
This PR resolves #379 by running nightly tests against all three daily snaps (master, stable-12, and stable-11), helping us catch regressions coming down the pipe from upstream Nextcloud.
=> CI: test daily snaps on a daily basis

snap/snapcraft.yaml, src/php/config/php.ini
All known blocking regressions in v12 have finally been fixed, so this PR resolves #280 by updating Nextcloud to v12.0.4. It also enables the opcache and tweaks the parameters as Nextcloud itself suggests.
Please test this PR using the `stable/pr-388` channel:
$ sudo snap install nextcloud --channel=stable/pr-388
Or if you already have it installed (note that you can't go back if you do this, Nextcloud doesn't support downgrades!):
$ sudo snap refresh nextcloud --channel=stable/pr-388
We need to particularly ensure that it works on a clean install as well as upgrades from the current stable. To anyone who _does not want to upgrade_ to v12, you don't have to, but you [need to take action](https://kyrofa.com/posts/nextcloud-snap-to-be-updated-to-v12).
=> nextcloud: update to 12.0.4

snap/snapcraft.yaml
This PR resolves #396, getting rid of warnings when using `occ`, which were annoying and often misled people into thinking something was wrong.
Please test this PR using the `stable/pr-397` channel:
$ sudo snap install nextcloud --channel=stable/pr-397
$ sudo snap refresh nextcloud --channel=stable/pr-397
=> php: enable pcntl

snap/snapcraft.yaml
This PR resolves #389 by updating Nextcloud to v11.0.6.
Test this PR with the `11/stable/pr-403` channel:
$ sudo snap install nextcloud --channel=11/stable/pr-403
If you already have it installed:
$ sudo snap refresh nextcloud --channel=11/stable/pr-403
=> [11] nextcloud: update to 11.0.6

snap/snapcraft.yaml
This PR is a backport of #397, resolving #396 for 11 by getting rid of warnings when using `occ`, which were annoying and often misled people into thinking something was wrong.
Test this PR with the `11/stable/pr-404` channel:
sudo snap install nextcloud --channel=11/stable/pr-404
sudo snap refresh nextcloud --channel=11/stable/pr-404
=> [11] php: enable pcntl

snap/plugins/x-php.py, snap/snapcraft.yaml
- Enables the LDAP module in PHP, which allows the "LDAP user and group backend" app to be enabled
=> php: enable ldap support

snap/snapcraft.yaml
This PR resolves #61 by enabling PHP's support for freetype. This is a requirement for Nextcloud v13.
=> php: add freetype support

README.md
Tests could not be run as described in README.md under Hacking, as
a dependency, xvfb, was missing. Now added.
Closes nextcloud/nextcloud-snap#460
=> fix: Add xvfb to test dependencies in README

snap/snapcraft.yaml
This is a backport of #478 to v11, resolving #477 for v11.
=> [11] apache: update to 2.4.29

snap/snapcraft.yaml
This PR resolves #470 by bringing the v11 snap up to date.
Please test using the `11/beta/pr-474` channel:
$ sudo snap install nextcloud --channel=11/beta/pr-474
$ sudo snap refresh nextcloud --channel=11/beta/pr-474
=> [11] nextcloud: update to 11.0.7

README.md, src/apache/conf/httpd.conf, src/apache/conf/ssl.conf, src/mysql/support-files/mysql.server, tests/Rakefile
Throw away trailing whitespace that git complained about.
Files containing trailing whitespace were identified using
```
grep -r '\s$' .
```
in the root of the repository.
Closes nextcloud/nextcloud-snap#487
=> Clean up trailing whitespace

snap/snapcraft.yaml
This PR fixes #526 by stopping using `httpd-wrapper` instead of `run-httpd`, which waits for services that will never come when stopping.
=> apache: stop waiting for services when stopping

snap/snapcraft.yaml
This PR is a backport of #527, fixing #526 for v11.
=> [11] apache: stop waiting for services when stopping

snap/snapcraft.yaml
Backport of #497, fixing #495 for v11.
=> [11] apache: upgrade to 2.4.33

src/nextcloud/bin/nextcloud-cron, src/nextcloud/bin/occ, src/php/bin/run-php, src/php/config/php.ini
PHP-FPM currently supports configuring a memory limit using `snap set`. However, CLI utilities (specifically `occ` and the cron job) use a different configuration file, and don't support changing the memory limit.
This PR fixes #550 by adding support for the same memory limit configuration to CLI utilities.
=> php: use configured memory limit for PHP CLI utilities

snap/snapcraft.yaml
This PR resolves #439 by updating Nextcloud to v13.0.2. Please test using the `13/candidate` channel:
$ sudo snap install nextcloud --channel=13/candidate
$ sudo snap refresh nextcloud --channel=13/candidate
=> nextcloud: update to 13.0.2

src/mysql/bin/start_mysql, src/mysql/utilities/mysql-utilities, src/nextcloud/bin/manual-install, src/php/bin/start-php-fpm
The process of actually firing MySQL up includes upgrading its schema, after which it's restarted. If other daemons fire up at the right time, they could already be relying on MySQL's presence when it restarts out from under them.
This PR fixes #607 by ensuring that other daemons don't consider MySQL ready until after it has
completed this logic.
=> mysql: don't consider mysql available until after restart

src/mysql/bin/start_mysql, src/mysql/utilities/mysql-utilities, src/nextcloud/bin/manual-install, src/php/bin/start-php-fpm
This PR is a backport of #608, fixing #607 for v12.
=> [12] mysql: don't consider mysql available until after restart

snap/snapcraft.yaml
Compile PHP with FTP support to allow mounting FTP locations as external storage.
When merged, this should fix #503
=> Add FTP support in PHP

snap/snapcraft.yaml
This PR is a backport of #646, resolving #643 for v12.
=> [12] apache: update to 2.4.34

snap/snapcraft.yaml, src/nextcloud/bin/occ, src/php/utilities/php-utilities, tests/spec/maintenance_mode_spec.rb
The `nextcloud.occ` command is often used to alter the Nextcloud config, which is a .php file. As such, it's subject to the same opcache settings as the rest of PHP, which doesn't even look at the tree to see if files have changed (`opcache.validate_timestamps=0`). As a result, any change made to `config.php` without restarting PHP goes unnoticed, which includes changes like enabling maintenance mode.
This PR fixes #486 by assuming the config has changed after using `nextcloud.occ`, and invalidating the opcache for the config so that it's reloaded.
=> occ: don't require PHP restart for maintenance mode

.circleci/config.yml
This PR resolves #697 by using snapcraft's Docker images instead of installing snapcraft in the Xenial container. It also ensures that tracebacks are always shown.
=> ci: use snapcraft docker images

snap/snapcraft.yaml
Update php to version 7.1.22, fixing security issues.
Fixes: nextcloud/nextcloud-snap:#711
=> php: Update to 7.1.22

snap/snapcraft.yaml
Fixes #691 
This time against the right branch.
=> redis: update to 4.0.11

snap/snapcraft.yaml, src/import-export/bin/export-data, src/import-export/bin/import-data, src/mysql/bin/run-mysql, tests/spec/import_export_spec.rb, tests/spec/spec_helper.rb
This PR resolves #185 by adding two new commands to the snap: `nextcloud.export` and `nextcloud.import`. They're pretty bare-bones right now, but they allow one to migrate between snap installs pretty easily by exporting the apps, database, config, and raw data. Note that this does not cover transferring other settings, like HTTPS certificates.
See `nextcloud.export -h` and `nextcloud.import -h` for more information. Please test this PR using the `beta/pr-688` channel:
$ sudo snap install nextcloud --channel=beta/pr-688
$ sudo snap refresh nextcloud --channel=beta/pr-688
=> Add the ability to import/export install

snap/snapcraft.yaml
This PR resolves #768, making the version more useful for non-stable snaps.
=> snapcraft.yaml: use git version instead of hard-coding

.circleci/config.yml, .travis/cron.sh
This PR resolves #825 by disabling daily v12 (it's no longer supported) and enabling daily v14 and v15.
=> ci: enable daily v14 and v15

snap/snapcraft.yaml
This PR resolves #835 by updating PHP to the latest 7.1 release.
=> php: update to 7.1.26

snap/plugins/x-php.py, snap/snapcraft.yaml
This PR fixes #792 by enabling large file support for PHP on 32-bit systems. It also enables it for any extensions being built.
Please test this PR using the `beta/pr-862` channel:
$ sudo snap install nextcloud --channel=beta/pr-862
$ sudo snap refresh nextcloud --channel=beta/pr-862
=> php: enable large file support on 32-bit systems

snap/snapcraft.yaml, src/apache/utilities/apache-utilities, src/common/utilities/common-utilities, src/import-export/bin/export-data, src/import-export/bin/import-data, src/mysql/utilities/mysql-utilities, src/nextcloud/bin/nextcloud-fixer, src/nextcloud/utilities/nextcloud-utilities, src/php/utilities/php-utilities, src/redis/utilities/redis-utilities
This PR resolves #812 by updating Nextcloud to the latest v15 release. It also adds logic to nextcloud-fixer to run the `convert-filecache-bigint` job automatically. Note that as of v15, Nextcloud shows a warning that imagick is not installed. This is unfortunate, but expected in the snap.
Please test this PR with the `beta/pr-865` channel:
$ sudo snap install nextcloud --channel=beta/pr-865
$ sudo snap refresh nextcloud --channel=beta/pr-865
=> nextcloud: update to 15.0.2

src/nextcloud/bin/nextcloud-fixer
This PR resolves #875 since disabling the theming app prevents the warning about imagick being required unless someone requires and enables the app.
Please test this PR using the `beta/pr-876` channel:
$ sudo snap install nextcloud --channel=beta/pr-876
$ sudo snap refresh nextcloud --channel=beta/pr-876
On a fresh install, the theming app should be disabled and no warning should appear. One should still be able to enable it and use theming, but then the warning appears, which actually seems fine at that point. On an upgrade from `stable`, the theming app should still be enabled and the warning _should_ appear.
=> nextcloud-fixer: disable theming app on new installs

snap/snapcraft.yaml
This PR resolves #889 by updating Nextcloud to the latest v15 release.
Please test this PR using the `beta/pr-890` channel:
$ sudo snap install nextcloud --channel=beta/pr-890
$ sudo snap refresh nextcloud --channel=beta/pr-890
=> nextcloud: update to 15.0.4

CHANGELOG, README.md, snap/snapcraft.yaml
- nextcloud: update to 15.0.5
- mysql: update to 5.7.25
- redis: update to 4.0.13
Please read [this wiki topic](https://github.com/nextcloud/nextcloud-snap/wiki/Testing-pull-requests) for how to test/evaluate this PR.
=> Release 15.0.5snap1

snap/snapcraft.yaml
This PR resolves #919 by updating Nextcloud to the latest v14 release.
=> nextcloud: update to 14.0.8

snap/snapcraft.yaml
This PR resolves #920 by updating Nextcloud to the latest v13 release.
=> nextcloud: update to 13.0.12

src/apache/conf/ssl.conf, tests/spec/change_port_spec.rb, tests/spec/spec_helper.rb
Not redirecting Lets-Encrypt challenge requests in ssl.conf.
Made this change referencing the [RewriteRule documentation](https://httpd.apache.org/docs/2.4/mod/mod_rewrite.html#RewriteRule).
**I didn't find a way to test this change locally since I'm using Ubuntu 18.04**. Could someone who has a better setup test this?
I think it's possible to write a test for this as well, but I didn't write one since I couldn't get the snap to build.
=> apache: don't redirect Let's Encrypt to HTTPS 

src/apache/conf/ssl.conf
Security is always a balancing act. The current cipher list in the snap prioritizes older clients while maintaining reasonable security for all. These settings are routinely verified using both [SSL Labs](https://www.ssllabs.com/ssltest/) and [testssl.sh](https://testssl.sh/), and the snap continues to get an A+ rating on SSL Labs. However, one of the ways we support older clients is by still using TLS 1.0 and 1.1, and also using CBC ciphers.
It's been a few years, and as several folks have pointed out, it's time to re-evaluate this balancing act for the cipher list in particular. To go through this exercise, I started with the modern config from Mozilla's [config generator](https://mozilla.github.io/server-side-tls/ssl-config-generator/), locked it down enough that nothing could possibly …
=> apache: disable TLS 1.0 and 1.1 and strengthen ciphers

CHANGELOG, snap/snapcraft.yaml, src/apache/conf/ssl.conf, tests/spec/change_port_spec.rb, tests/spec/spec_helper.rb
- apache: disable TLS 1.0 and 1.1 and strengthen ciphers
- apache: don't redirect Let's Encrypt to HTTPS
- php: update to 7.2.16
=> Release 15.0.5snap2

.circleci/config.yml, .travis/cron.sh
This PR resolves #964 by removing the generation and testing of v13 daily builds. v13 is no longer supported.
=> ci: disable v13 dailies

snap/snapcraft.yaml
This PR resolves #986 by updating Nextcloud to the latest v14 release.
=> nextcloud: update to 14.0.10

snap/snapcraft.yaml
This PR resolves #1003 by updating Nextcloud to the latest v15 release.
=> nextcloud: update to 15.0.8

src/https/certbot_nextcloud_plugin/webroot.py, src/https/setup.py
Older clients saved options unique to the custom webroot plugin that are used for renewals. This PR fixes #1012 by re-introducing it for backward compatibility for such clients. Certbot's built-in webroot plugin is used for new certificates.
=> certbot: re-introduce custom webroot plugin

src/mysql/my.cnf
This ensures that the error log will be stored within MySQL's data directory, which can be relied on to always exist.
Fixes #1000.
Signed-off-by: Tore Anderson <tore@fud.no>
=> mysql: explicitly configure error log file name

src/mysql/bin/start_mysql
Ensure that the generated MySQL root password is only written to `$SNAP_DATA/mysql/root.ini` if the root password was successfully set in the database itself.
The previous behaviour was to write out the password to `root.ini` unconditionally. This sabotaged the _revert-on-failure_  logic (`rm -rf "$SNAP_DATA"/mysql/*`) as the `root.ini` file would be recreated immediately afterwards, in turn preventing subsequent attempts of initialising the database (e.g., using `snap restart` nextcloud) fail with `[ERROR] --initialize specified but the data directory has files in it. Aborting.`.
=> mysql: only write root password to root.ini if successfully set

snap/snapcraft.yaml
PHP's GMP module (and libgmp) is required for SFTP (a core feature) as well as the bookmarks app. The library is small and doesn't appear to be a security concern. This PR resolves #1112 by enabling it.
=> php: enable gmp

snap/snapcraft.yaml
This PR resolves #972 by updating Nextcloud to the latest v16 release.
=> nextcloud: update to 16.0.5

snap/snapcraft.yaml, src/common/utilities/common-utilities, src/import-export/bin/import-data, src/nextcloud/bin/occ, src/php/config/php.ini, src/php/utilities/php-utilities, tests/spec/maintenance_mode_spec.rb, tests/spec/spec_helper.rb
Not checking timestamps seems like a sensible optimization given that snaps are read-only. However, this ignores the fact that apps can be installed and updated, and those are also PHP. The opcache needs to be invalidated in that case. This PR resolves #1130 by updating the PHP configuration to check file timestamps.
=> php: check file timestamps for opcache

snap/snapcraft.yaml
Backport of #1147, resolving #1143 for v15.
=> mysql: update to 5.7.28

snap/snapcraft.yaml, src/nextcloud/bin/nextcloud-fixer, src/nextcloud/bin/occ, src/nextcloud/bin/setup-nextcloud
Nextcloud upgrades don't update apps properly (see nextcloud/server#18673). This results in a very poor upgrade experience if a bundled app needs to update. This PR works around this issue by updating apps automatically.
=> nextcloud-fixer: update all apps

src/nextcloud/bin/nextcloud-fixer, src/nextcloud/fixes/existing-install/1_upgrade.sh, src/nextcloud/fixes/existing-install/2_update-apps.sh, src/nextcloud/fixes/existing-install/3_add-missing-indices.sh, src/nextcloud/fixes/existing-install/README, src/nextcloud/fixes/existing-install/maintenance/1_convert-filecache-bigint.sh, src/nextcloud/fixes/existing-install/maintenance/README, src/nextcloud/fixes/fresh-install/1_disable-theming.sh, src/nextcloud/fixes/fresh-install/2_add-missing-indices.sh, src/nextcloud/fixes/fresh-install/3_convert-filecache-bigint.sh, src/nextcloud/fixes/fresh-install/README
This PR fixes #1214 by making sure an upgrade and app update happens before anything else. It also refactors nextcloud-fixer to be a more easily-expanded set of fixes (hacks) by making them all shell scripts instead of lines in the same file.
=> nextcloud-fixer: upgrade and update apps before anything else

README.md
This PR resolves #1121 by mentioning that the `removable-media` plug also covers the `/mnt` directory.
=> README: removable-media also covers /mnt

snap/snapcraft.yaml
This PR is a backport of #1218, resolving #1217 for v15.
=> mysql: update to 5.7.29

src/common/utilities/common-utilities, src/nextcloud/fixes/existing-install/99_notify_admins.sh, src/nextcloud/fixes/fresh-install/99_record_snap_version.sh, src/nextcloud/utilities/nextcloud-utilities
The main sell of the Nextcloud snap is that is updates automatically in a transactional manner. A side effect of this is that admins could completely miss the fact that an update occurred, and if the update did something they didn't expect they don't immediately know what to blame.
This PR resolves #1220 by adding the ability to notify all admins when the snap updates, making sure they know how to revert if something doesn't work properly.
=> nextcloud: notify admins upon update

snap/snapcraft.yaml, src/hooks/bin/pre-refresh
Nextcloud's update process doesn't do a good job of ensuring apps are updated properly and re-enabled after the update. It seems to work best if apps are already as up-to-date as they can be. This PR resolves #1243 by taking a moment to make sure all apps are up-to-date if we know we're about to be refreshed.
=> hooks: add pre-refresh hook to update apps

snap/snapcraft.yaml
This PR resolves #1236 by updating Nextcloud to the latest v16 release.
=> nextcloud: update to 16.0.8

src/nextcloud/utilities/nextcloud-utilities
Nextcloud supports creating a user with spaces in the username, which confuses the update notification. This PR fixes #1260 by updating it to support spaces.
=> nextcloud: support notifying users with spaces in username

snap/snapcraft.yaml
This PR resolves #1129 by updating Nextcloud to the latest v17 release.
=> nextcloud: update to 17.0.3

snap/snapcraft.yaml
This PR updates the Redis framework of the snap; that is:
- **phpredis** to 5.1.1 (from 3.1.4)
- **redis** to 5.0.7 (from 4.0.13)
@kyrofa tell me if it makes sense to update both components in the same PR or if you want separate ones.
Redis 4.x is approaching EOL, as per https://redis.io/download#other-versions:
> Redis 4.0 was released as GA in July 2017, newcomers should use Redis 5, but Redis 4 is
> currently the most production-proven release and will be updated for the next year until
> Redis 6 will be out.
I've tested this as a fresh install and everything seems fine, but I still have to test it on my own instance.
This would resolve #802
=> Update Redis framework

snap/snapcraft.yaml
This PR resolves #1277 by updating Nextcloud to the latest v17 release.
=> nextcloud: update to 17.0.5

snap/snapcraft.yaml
This PR resolves #1292 by updating Apache to the latest 2.4 release.
=> apache: update to 2.4.43

snap/snapcraft.yaml
This PR resolves #1247 by updating Nextcloud to the latest v18 release.
=> nextcloud: update to 18.0.4

snap/snapcraft.yaml
This PR resolves #1307 by updating Nextcloud to the latest v17 release.
=> nextcloud: update to 17.0.6

snap/snapcraft.yaml
This PR is a backport of #1287, resolving #1286 for v16.
=> redis: update to 5.0.8

snap/snapcraft.yaml
This PR resolves #1321 by updating Nextcloud to the latest v16 release.
=> nextcloud: update to 16.0.9

.circleci/config.yml, tests/spec/spec_helper.rb
They're apparently unwilling to fix their broken image, so we need to upgrade the one we use and hope it doesn't break other things.
=> tests: update CircleCI image

src/nextcloud/utilities/nextcloud-utilities
This PR resolves #1345 by making 5 minutes the default cron period for new installs. Existing installs should remain unchanged, and the admin can always configure it as they see fit.
=> nextcloud: cron should run every 5 minutes by default

src/nextcloud/fixes/existing-install/4_regenerate-assets.sh
This PR resolves #1323 by regenerating the asset cache when the snap starts up. Without this, reverting the snap can result in an older Nextcloud attempting to use the assets of a newer Nextcloud, which is an experience that generally makes one sad.
=> nextcloud: regenerate asset cache on startup

CHANGELOG, src/nextcloud/fixes/existing-install/4_regenerate-assets.sh, src/nextcloud/utilities/nextcloud-utilities
- nextcloud: regenerate asset cache on startup
- nextcloud: cron should run every 5 minutes by default
=> Release 18.0.4snap3

.circleci/Dockerfile, .circleci/config.yml, snap/plugins/x-apache.py, snap/snapcraft.yaml, src/mysql/bin/run-mysqldump
@kyrofa I known this won't be merged yet (context here https://github.com/nextcloud/nextcloud-snap/issues/755#issuecomment-583815600) but I thought that I would leave my work here and (try to) maintain it, so the changes are ready when we feel confident about the upgrade.
Meanwhile, it can also be tested by someone else than me.
Also, with the OpenSSL upgrade, we get TLS 1.3 without any changes on the Apache config, so this would also resolve #1021
=> snap: upgrade to core18

.circleci/config.yml, .travis/cron.sh
This PR resolves #1362 by disabling v16 dailies (v16 is no longer supported).
=> tests: remove v16 dailies

snap/snapcraft.yaml
This PR resolves #1360 by updating Nextcloud to the latest v16 release.
=> nextcloud: update to 16.0.10

snap/snapcraft.yaml
This PR resolves #1367 by updating Nextcloud to the latest v16 release.
=> nextcloud: update to 16.0.11

snap/snapcraft.yaml
This PR is a backport of #1329, resolving #1320 for v17.
=> mysql: update to 5.7.30

snap/plugins/apache.py, snap/plugins/php.py, snap/plugins/redis.py
Snapcraft 4.0.4 was released and broke our CI. See https://forum.snapcraft.io/t/18063 for more information.
=> snap: rewrite plugins to workaround snapcraft breakage

snap/snapcraft.yaml
This PR resolves #1374 by updating Nextcloud to the latest v18 release.
=> nextcloud: update to 18.0.6

snap/snapcraft.yaml
This PR resolves #1408 by updating Nextcloud to the latest v19 release.
=> nextcloud: update to 19.0.1

src/mysql/bin/start_mysql, src/mysql/support-files/mysql.server
Snaps are not properly confined across distributions. This has led to bad behavior in the Nextcloud snap where, if installed on a Debian system (which does not have apparmor in its kernel) that has MySQL installed, the snap will find the host's MySQL configuration files. This isn't an issue on Ubuntu or other systems where snap security is real, but sadly is [not considered a bug by snapd developers](https://bugs.launchpad.net/snapd/+bug/1819734), so we need to figure out a solution to it on our own.
This PR resolves #913 by explicitly not loading any config files except the one in the snap.
=> mysql: ignore config files on host

snap/snapcraft.yaml
This PR resolves #1442 by updating Nextcloud to v19.0.2.
=> nextcloud: update to 19.0.2

README.md, snap/snapcraft.yaml
This PR resolves #1452 by updating Nextcloud to the latest v19 release.
=> nextcloud: update to 19.0.3

README.md, snap/snapcraft.yaml
This PR resolves #1451 by adding the `network-observe` interface to the PHP-FPM service. This is not automatically connected upon install, but can be optionally connected if one would like to utilize the network monitoring functionality built into the Nextcloud system app.
To test, install/refresh the snap from the `latest/beta/pr-1455` channel, and connect the `network-observe` interface. Then visit the system app and confirm that the network information is filled out as expected.
=> snapcraft.yaml: enable network monitoring

snap/snapcraft.yaml
This PR resolves #1459 by building support for argon2 into PHP.
Test this PR using the `latest/beta/pr-1461` channel:
$ sudo snap install nextcloud --channel=latest/beta/pr-1461
$ sudo snap refresh nextcloud --channel=latest/beta/pr-1461
=> php: include support for argon2

src/php/config/php.ini
This PR fixes #1450 by disabling output buffering in PHP. This has been a [long-standing configuration recommendation](https://docs.nextcloud.com/server/19/admin_manual/configuration_files/big_file_upload_configuration.html?highlight=output_buffering#configuring-php) that the snap never satisfied.
=> php: disable output buffering

src/mysql/bin/start_mysql, src/mysql/utilities/mysql-utilities
There are a number of examples where the mysql service in the snap fails to fire up because, despite the mysql socket and pid being available, mysqld doesn't seem to respond properly. This PR fixes #1478 by adding a simple command to the status check to ensure there's no race condition.
Builds of this PR for all architectures are available in the `beta/pr-1481` channel. To test it, run:
$ sudo snap install nextcloud --channel=latest/beta/pr-1481
$ sudo snap refresh nextcloud --channel=latest/beta/pr-1481
=> mysql: ensure mysqld responds before considering it up

snap/snapcraft.yaml, src/hooks/bin/pre-refresh
Trying to update apps or upgrade Nextcloud while apps.nextcloud.com is down is a recipe for problems. This PR resolves #1485 by canceling a refresh if it seems to be down.
=> hooks: check that apps.nextcloud.com is up before refreshing

snap/snapcraft.yaml, src/php/config/php.ini, tests/spec/change_mode_spec.rb
This PR resolves #1477 by updating PHP to the latest v7.4 release.
Test this PR by installing from the `beta/pr-1483` channel:
$ sudo snap install nextcloud --channel=latest/beta/pr-1483
$ sudo snap refresh nextcloud --channel=latest/beta/pr-1483
=> php: update to 7.4.11

snap/snapcraft.yaml, src/apache/bin/run-httpd, src/apache/conf/httpd.conf, src/common/utilities/common-utilities, src/hooks/bin/post-refresh, src/import-export/bin/export-data, src/logrotate/bin/run-logrotate, src/logrotate/config/logrotate.conf, src/logrotate/utilities/logrotate-utilities, src/migrations/bin/run-snap-migrations, src/migrations/migrations/19.0.3snap3/1_move-logs.sh, src/mysql/bin/reload-mysql, src/mysql/bin/run-mysql, src/mysql/bin/start_mysql, src/mysql/my.cnf, src/mysql/utilities/mysql-utilities, src/nextcloud/bin/nextcloud-cron, src/nextcloud/config/autoconfig.php, src/nextcloud/config/config.php, src/php/bin/reload-php, src/php/bin/start-php-fpm, src/php/config/php-fpm.conf, src/php/config/php.ini, src/php/utilities/php-utilities, src/redis/bin/start-redis-server, src/redis/config/redis.conf, src/redis/utilities/redis-utilities
This PR fixes #1476 by adding logrotate to the snap, and setting up all service logs to be rotated. It also reorganizes the existing logs to make this more straight-forward.
=> apache,php,mysql,redis,nextcloud: add log rotation

src/migrations/bin/run-snap-migrations
Nextcloud is strict about what makes for a valid upgrade. Minor version jumps are okay (i.e. within the same major version). Single major version jumps are also okay, but not more than one (e.g. 18 to 19 is okay, but not 18 to 20). Downgrades are never okay.
This PR resolves #1393 by adding a check to the migration runner (which is run by the post-refresh hook) to ensure that the snap doesn't allow such a refresh to occur, which should relieve a lot of potential stress and reverts.
=> migrations: sanity check nextcloud version before upgrade

snap/snapcraft.yaml
This PR resolves #1487 by updating Nextcloud to the latest v19 release.
=> nextcloud: update to 19.0.4

snap/snapcraft.yaml
This PR is a backport of #1409, resolving #1404 for v18.
=> mysql: update to 5.7.31

src/migrations/bin/run-snap-migrations
The current migration version check assumes a version of the format major.minor.patch, which isn't the case when it comes to daily builds. This PR fixes #1505 by updating the logic to take that into account, and bailing the version check entirely if major versions can't be reliably extracted.
=> migrations: support daily versions

README.md, snap/snapcraft.yaml
This PR resolves #1496 by updating Nextcloud to the latest v18 release.
=> nextcloud: update to 18.0.10

src/logrotate/bin/run-logrotate
This PR fixes #1508 by removing the status file if logrotate exits non-zero. This means we may miss a rotation, but that seems a small price to pay for handling this error.
To test this PR, install the snap from the `latest/beta/pr-1513` channel:
$ sudo snap install nextcloud --channel=latest/beta/pr-1513
$ sudo snap refresh nextcloud --channel=latest/beta/pr-1513
=> logrotate: remove status file if it seems corrupted

src/logrotate/bin/run-logrotate
This PR fixed #1508 by skipping the first line of the logrotate status file when ensuring that each log file exists.
=> logrotate: skip first line of status file when cleaning

.travis/cron.sh, CHANGELOG, snap/snapcraft.yaml, src/logrotate/bin/run-logrotate, src/migrations/bin/run-snap-migrations, src/mysql/bin/reload-mysql, src/mysql/bin/run-mysql, src/mysql/bin/run-mysqldump, src/mysql/bin/start_mysql
- logrotate: skip first line of status file when cleaning
- logrotate: remove status file if it seems corrupted
- mysql: update to 5.7.32
- migrations: support daily versions
=> Release 19.0.4snap2

snap/snapcraft.yaml, tests/spec/change_php_memory_limit_spec.rb, tests/spec/enable_https_spec.rb, tests/spec/import_export_spec.rb, tests/spec/login_spec.rb
This PR resolves #1474 by updating Nextcloud to v20. Note that this will not be merged until at least the first point release, but this gives us a place to gather feedback.
=> nextcloud: update to 20.0.1

src/nextcloud/utilities/nextcloud-utilities
There are situations where `occ --output=json` produces invalid json (see #1504 and https://github.com/nextcloud/server/issues/23596). Work around these issues using jq.
=> nextcloud: workaround invalid json from occ

.circleci/config.yml, tests/spec/change_php_memory_limit_spec.rb, tests/spec/enable_https_spec.rb, tests/spec/import_export_spec.rb, tests/spec/login_spec.rb
This PR resolves #1519 by updating tests to pass for both v20 and earlier major versions, and enabling daily tests against v20.
=> tests: enable daily v20 tests

snap/snapcraft.yaml
This PR resolves #1551 by updating Nextcloud to the latest v20 release.
=> nextcloud: Update to 20.0.2

snap/snapcraft.yaml
This PR is a backport of #1554, resolving #1550 for v19.
=> php: update to 7.4.13

snap/snapcraft.yaml
This PR resolves #1561 by updating Nextcloud to the latest v18 release.
=> nextcloud: update to 18.0.11

snap/snapcraft.yaml
This PR resolves #1563 by updating Nextcloud to the latest v19 release.
=> nextcloud: update to 19.0.5

src/nextcloud/fixes/existing-install/6_add-missing-primary-keys.sh
This PR resolves #1565 by running `occ db:add-missing-primary-keys` on behalf of the user on existing installs.
=> nextcloud-fixer: run db:add-missing-primary-keys

CHANGELOG, src/nextcloud/fixes/existing-install/6_add-missing-primary-keys.sh
- nextcloud-fixer: run db:add-missing-primary-keys
=> Release 20.0.2snap2

snap/snapcraft.yaml
This PR resolves #1575 by updating Nextcloud to the latest v20 release.
=> nextcloud: update to 20.0.3

snap/snapcraft.yaml
This PR resolves #1579 by updating Nextcloud to the latest v18 release.
=> nextcloud: update to 18.0.12

snap/snapcraft.yaml
This PR resolves #1581 by updating Nextcloud to the latest v19 release.
=> nextcloud: update to 19.0.6

src/mysql/my.cnf
This PR resolves #1571 by updating the MySQL transaction isolation to the value recommended by Nextcloud. It might improve MySQL performance in the snap.
In order to test this PR, install the snap from the `latest/beta/pr-1583` channel:
$ sudo snap install nextcloud --channel=latest/beta/pr-1583
$ sudo snap refresh nextcloud --channel=latest/beta/pr-1583
=> mysql: use READ-COMMITTED instead of REPEATABLE-READ

snap/snapcraft.yaml
This PR resolves #1594 by updating Nextcloud to the latest v20 release.
=> nextcloud: update to 20.0.4

CHANGELOG, README.md, snap/snapcraft.yaml, src/mysql/my.cnf
- nextcloud: update to 20.0.4
- mysql: use READ-COMMITTED instead of REPEATABLE-READ
=> Release 20.0.4snap1

snap/snapcraft.yaml
This PR resolves #1619 by updating Nextcloud to the latest v20 release.
=> nextcloud: update to 20.0.6

snap/snapcraft.yaml
This PR resolves #1632 by updating Nextcloud to the latest v20 release.
=> nextcloud: update to 20.0.7

src/php/utilities/php-utilities
On my system, when a reload is attempted it fails with the following log entries:
```
Feb 28 00:00:16 yami systemd[1]: Reloading Service for snap application nextcloud.php-fpm.
Feb 28 00:00:16 yami nextcloud.php-fpm[384399]: /snap/nextcloud/26119/bin/reload-php: 57: kill: Illegal number: php_pid
Feb 28 00:00:16 yami systemd[1]: snap.nextcloud.php-fpm.service: Control process exited, code=exited, status=2/INVALIDARGUMENT
Feb 28 00:00:16 yami systemd[1]: Reload failed for Service for snap application nextcloud.php-fpm.
Feb 28 00:00:16 yami systemd[1]: Cannot find unit for notify message of PID 384398, ignoring.
Feb 28 00:00:16 yami snapd[802]: taskrunner.go:271: [change 92 "reload-or-restart of [nextcloud.php-fpm]" task] failed: exit status 1
Feb 28 00:00:17 yami …
```
=> Correctly obtain the PHP-FPM pid before sending a signal

snap/snapcraft.yaml
This PR resolves #1656 by updating Nextcloud to the latest v20 release.
=> nextcloud: update to 20.0.8

src/logrotate/config/logrotate.conf
This PR fixes #1668 by adding the Apache access log to the logrotate configuration file.
=> logrotate: rotate apache access log

.circleci/Dockerfile
The snapcraft godeps plugin only works with v1.15, see [LP: #1922150](https://bugs.launchpad.net/bugs/1922150) for more information.
=> circleci: pin go to 1.15

.circleci/Dockerfile, CHANGELOG, README.md, snap/snapcraft.yaml, src/logrotate/config/logrotate.conf, src/php/utilities/php-utilities
- logrotate: rotate apache access log
- redis: update to 5.0.12
- nextcloud: update to 20.0.8
- Correctly obtain the PHP-FPM pid before sending a signal
- php: update to 7.4.15
=> Release 20.0.8snap1

snap/snapcraft.yaml
This PR resolves #1727 by upgrading Nextcloud to the latest v21 release.
=> nextcloud: update to 21.0.1

src/mysql/my.cnf
This was disabled in v5.7, and is supposed to be disabled in v8 when initialized with the method we're using. See [the docs](https://dev.mysql.com/doc/refman/8.0/en/replication-options-binary-log.html), particularly this quote:
> In earlier MySQL versions, binary logging was disabled by default, and was enabled if you specified the --log-bin option. From MySQL 8.0, binary logging is enabled by default, whether or not you specify the --log-bin option. The exception is if you use mysqld to initialize the data directory manually by invoking it with the --initialize or --initialize-insecure option, when binary logging is disabled by default.
We [do indeed initialize mysql that way](https://github.com/nextcloud/nextcloud-snap/blob/master/src/mysql/bin/start_mysql#L17), but the binlog is still …
=> mysql: disable binary logging

src/nextcloud/bin/manual-install
Nextcloud's `occ maintenance:install` doesn't support autoconfig.php, which means there's currently no way to specify a data directory for the snap if one wants to install it from the CLI. This PR resolves #1670 by adding support for this as a new option to the manual-install script.
=> nextcloud: support specifying data directory in manual-install

src/mysql/my.cnf
This was not enabled by default in mysql 5.7.x but it is on version 8.0.x:
https://dev.mysql.com/doc/refman/8.0/en/performance-schema-quick-start.html
This impacts low memory devices, so it should be disabled in the snap; we can latter think about activating it when using the snap in debug mode.
Fixes #1836
=> mysql: disable performance_schema

.github/spawn-dailies.sh, .github/workflows/daily.yml
This PR resolves #1827 by re-implementing daily builds using GitHub Actions (this used to be done in Travis before it shutdown).
=> ci: enable daily builds

snap/snapcraft.yaml
We forgot to backport this to 21.
=> Upgrade PHP to 8.0.13

.github/workflows/test.yml, tests/integration/spec_helper.rb
There are some dependencies leaking into the snap from the build host. Use LXD and build containers to isolate the snap from that type of thing.
=> ci: use snapcraft build container instead of destructive

snap/plugins/apache.py, snap/snapcraft.yaml
This was a mistake introduced in ff1d2a62736136b06ae46da732c8d0a08c88d877. Fix it.
=> snapcraft: move apache build/stage packages into plugin

snap/snapcraft.yaml
I guess we should be updating this too, now that https://github.com/nextcloud-snap/nextcloud-snap/pull/2084 was merged.
=> Update phpredis 5.3.7

.github/workflows/test.yml
Snapcraft v7 removed APIs used in our plugins without deprecating them. We need to rewrite our plugins to use new APIs (see #2122), but that will take time. Until then, pin our snapcraft use to v6.
=> ci: pin snapcraft to v6

src/nextcloud/utilities/nextcloud-utilities, tests/integration/change_php_memory_limit_spec.rb, tests/integration/enable_https_spec.rb, tests/integration/import_export_spec.rb, tests/integration/login_spec.rb, tests/integration/spec_helper.rb
The login labels changed in Nextcloud v25 such that these tests no longer pass. Start using the IDs instead, which remain consistent through at least the last few releases.
=> integration tests: use input ID instead of label

tests/integration/import_export_spec.rb, tests/integration/spec_helper.rb
We have some tests that reinstall the snap, in which case Nextcloud Fixer runs, which is something that causes maintenance mode to be enabled. If the timing is Just Right (or Wrong, as the case may be), maintenance mode will be enabled right as a test is trying to log in, which causes the test to fail. Just wait for the Fixer to finish before trying anything.
=> integration tests: wait for nextcloud fixer to finish

src/php/config/php.ini
[Nextcloud is written](https://github.com/nextcloud/server/blob/03390ee791405aa399e00cc1b0220ae9e3c8d85e/apps/settings/lib/Controller/CheckSetupController.php#L526-L535) not to warn about the interned strings buffer size if it is at least a quarter of the total opcache buffer size. This means we can resolve #2024 without needing to make the buffer size configurable, which seems like a win.
=> php: bump interned strings buffer to a quarter of opcache buffer

.github/workflows/daily.yml, .github/workflows/test-daily.yml, .github/workflows/test.yml
Github has deprecated 18.04 and to notify people is using brown outs, causing builds to fail. Update to 20.04. This should work fine given that we're building in a LXD container.
=> ci: use ubuntu 20.04 instead of 18.04

.github/workflows/daily.yml, .github/workflows/test-daily.yml, .github/workflows/test.yml, CHANGELOG, snap/snapcraft.yaml, src/php/config/php.ini
- php: bump interned strings buffer to a quarter of opcache buffer
- redis: update to 6.2.10
=> Release 25.0.3snap2

CHANGELOG, snap/snapcraft.yaml
- apache: update to 2.4.56
- redis: update to 6.2.11
- nextcloud: update to 25.0.4
=> Release 25.0.4snap1

snap/snapcraft.yaml
This PR resolves #2370 by updating Apache to the latest v2.4 release.
=> apache: update to 2.4.57

CHANGELOG, snap/snapcraft.yaml, src/apache/conf/httpd.conf
- nextcloud: update to 25.0.6
- mysql: update to 8.0.33
- apache: add mime type support for wasm
- redis: update to 6.2.12
=> Release 25.0.6snap1

src/https/utilities/https-utilities
Resolves https://github.com/nextcloud-snap/nextcloud-snap/issues/2417. Sorts certbot cert directories by modified time and takes the most recent one.
=> Use most recent certbot certs

.github/spawn-dailies.sh, .github/workflows/test-daily.yml
Fixes #2420 
Similar to changes by #2360. Hope that's fine.
Recommending squash and merge.
For NC24: Not sure how you handled that in past, but I suggest to keep for now as the `stable24` branche still get changes even if it's EOL (probably due enterprise).
=> ci: enable 27 dailies

.github/spawn-dailies.sh, .github/workflows/test-daily.yml
Dailies for Nextcloud 24 has been turned off since 12 July. See https://cloud.nextcloud.com/call/xs25tz5y#message_2014229.
=> Remove Nextcloud 24 dailies

.github/workflows/launchpad.yml
This is basically just a synchronization of the protected branches from github to launchpad, and the automatic snap builds take over from there. Notably, this does not cover automatic deploys of snaps from pull requests; that is a bit more complex due to the potential to leak secrets.
=> ci: automatically deploy pushes to launchpad

snap/snapcraft.yaml, src/patches/mysql-revert-BUG-34849343-Aligned_atomic-not-working-as-in.patch
Here I'm trying to apply the same solution that [the Ubuntu package used](https://bugs.launchpad.net/ubuntu/+source/mysql-8.0/+bug/2019203/comments/16) to fix a bug similar to [that observed by our users](https://github.com/nextcloud-snap/nextcloud-snap/issues/2405).
Their solution was to revert [commit be8348a7](https://github.com/mysql/mysql-server/commit/be8348a7c3e8510b998a063065b626a459631b32), so we will see if that also works for us.
In theory, a proper fix should be coming in the next mysql version ([8.0.35](https://bugs.mysql.com/bug.php?id=110752)), but we will also need to try that, as they only mention aarch64-based platforms.
We'll need to make sure we backport this fix to v25, which is where this issue was introduced.
=> mysql: revert commit be8348a7c3

.github/workflows/release-pr-snap.yml, .github/workflows/test.yml
This PR resolves #2521 by taking the snap created/tested in a pull request, and uploading it to a channel following the naming pattern `latest/beta/pr-<PR ID>`. This works even on distrusted forks due to the use of the `workflow_run` trigger. Once the pull request's CI finishes successfully, this job is triggered on the _master_ branch, which is trusted code. The job downloads the snap artifact from the pull request, and handles the upload and token access without ever running distrusted code. This keeps the risk of token leakage to a minimum.
Note that this only releases the snap built during the pull request's CI process, which is amd64.
=> ci: publish snaps from pull requests for testing

.github/workflows/release-pr-snap.yml
2df9c560119a2544774f11101006d9d25ab67cb1 used the Workflow Run info in the GitHub API to determine the pull request that triggered it. Sadly that information doesn't appear to be filled out properly if the pull request in question is coming from a fork. Use a more brute-force method instead, searching through every open pull request for the commit that triggered the workflow in question.
=> PR snap releaser: detect triggering pull request in fork-compatible way

.github/workflows/test.yml
The bug that was hitting us has been solved in 7.5.3: https://github.com/snapcore/snapcraft/issues/4285
We have to stick with 7.x, as 8.x will deprecate `core18` snaps.
If this works, we will need to update snap building options on Launchpad too.
Fixes #2122
=> snapcraft: use branch 7.x

snap/snapcraft.yaml
Apache only hosts the latest version of the HTTPD server on https://dlcdn.apache.org/httpd/ so use
http://archive.apache.org/dist/httpd/ istead, which holds all versions.
Fix #2579
=> apache: use archive site instead of dlcdn

CHANGELOG
- nextcloud: update to 26.0.8
- php: update to 8.1.25
- mysql: revert BUG#34849343 reversion
- mysql: update to 8.0.35
- redis: update to 6.2.14
- apache: update to 2.4.58
=> release 26.0.8snap1

.github/spawn-dailies.sh
- Enable dailies for Nextcloud 28, as they are already available.
- Disable dailies for Nextcloud 25, as this version is EOL.
=> Enable dailies for Nextcloud 28

.github/workflows/test-daily.yml
Missed that in my last PR, so here is the new one.
Not sure if you still want to target `develop`, just change it if you want to merge to `master` directly.
=> ci: add tests for nextcloud 28

snap/snapcraft.yaml
This resolved the nice warning in NC28 by installing the php sodium extension. 
Fix #2643
Required for #2641 
It is a recommended php module by Nextcloud:
> PHP module sodium (for Argon2 for password hashing. bcrypt is used as fallback, but if passwords were hashed with Argon2 already and the module is missing, your users can’t log in.)
=> php: enable sodium

README.md, src/apache/bin/httpd-wrapper, src/apache/conf/httpd.conf, src/apache/utilities/apache-utilities, src/hooks/bin/configure
Fix #1655
I used a few minutes and tried to implement a simple reverse proxy for the notiy_push component as a first step (see linked issue). It's probably all we can do. But this will already help a lot people to use the notify_push component **with encrypted https**!
In a later step we can maybe try to install and setup notify_push as additional component (maybe enabled by default). But 1. we would need to know the domain for the setup and 2. I have not the knowledge about the most programing stuff here. xP
By default, the snap does not enable notify_push reverse proxy. To enable it, run:
sudo snap set nextcloud http.notify-push-reverse-proxy=true
To disable it, run:
sudo snap set nextcloud http.notify-push-reverse-proxy=false
1. @kyrofa What should we do with test? It is not possible …
=> Add config to enable notify_push reverse proxy 

snap/snapcraft.yaml
[The latest stable is now Redis 7.2](https://redis.io/download/), so I think that it's time we move to the 7.0 branch.
Also lift the phpredis extension to version 6.0.2
Fixes #2647
=> redis: upgrade to 7.0.15

CHANGELOG
I've tested an upgrade from the `26/stable` channel (26.0.10) to the `26/beta` one (26.0.13) and it worked OK.
=> Release 26.0.13snap1

snap/snapcraft.yaml
=> Use cmake snap to build MySQL 8.0.37

src/nextcloud/config/config.php, src/nextcloud/fixes/existing-install/7_add_maintenance_window.sh
Fix #2658
~~Required~~ for #2641
=> nextcloud: add default config for `maintenance_window_start`

.github/spawn-dailies.sh, .github/workflows/test-daily.yml
Fix #2737
Leaving dailies for nextcloud 26 as they still get generated on nextcloud.
=> ci: enable dailies for nextcloud 29

src/apache/conf/httpd.conf
We weren't compressing JS files because we were missing the correct MIME type in the `AddOutputFilterByType` directive.
Fixes #2779
=> httpd.conf: update javascript MIME types to compress

snap/snapcraft.yaml
Fix #2744
Need to be tested, not sure if we need to enable something explicitely or if its enough to remove the disable lines.
=> php: enable sqlite3 & pdo-sqlite

.github/spawn-dailies.sh
fix #2896
-> also remove dailies for nextcloud 27 because EOL and the package isn't available anymore due #2891
~~Note: The tarball `latest-stable30.tar.bz2` ist not yet available. Currently asking @tobiasKaminsky for enabling daily those builds of that file.~~ Fixed!
=> ci: enable dailies for nextcloud 30

CHANGELOG, README.md, snap/snapcraft.yaml
I know it might be a bit early, but I just had the time to quickly make a release PR. You might want to wait a few more days, no problem.
The new version works flowless for me without any problem for my private production instance. Keep in mind that I have many third-party apps installed.
Additionally fixes #2933 and closes #2898 *(writing those here because they weren't mentoined in any commit message)*
=> Release 30.0.1snap1

.github/workflows/test.yml
actions/upload-artifact@v3 will be deprecated by December 5, 2024.
The breaking changes are documented [here](https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes). For our use case there shouldn't be problems, but who knows.
=> actions: upgrade upload-artifact to v4

.github/workflows/launchpad.yml
Second try at solving the problem we have with Launchpad just getting lightweight tags from the action. More context https://github.com/nextcloud-snap/nextcloud-snap/issues/2966#issuecomment-2502193356.
=> actions: workaround checkout action not fetching annotated tags

tests/integration/change_php_memory_limit_spec.rb, tests/integration/enable_https_spec.rb, tests/integration/import_export_spec.rb, tests/integration/login_spec.rb
The problem seems to be with the newest chromium 134. More context here: https://github.com/teamcapybara/capybara/issues/2800#issuecomment-2727634699 We should be able to remove the sleeps once the upstream problem is solved.
=> tests: workaround intermitent failing of integration tests

.github/workflows/test.yml
Does what it says. Made a PR a year ago already but it didn't get merged or reviewed. Another try, now that I know @kyrofa would accept it probably. :)
It's the same way like I've seen for ohter organizations.
=> run ci only on protected branches

.github/spawn-dailies.sh
Fix #3074 
Reference: https://cloud.nextcloud.com/call/xs25tz5y#message_3728500
=> ci: enable dailies for nextcloud 31

snap/snapcraft.yaml
What's Changed
[stable31] fix(mime-types): adjust compiled mime types and sign by @backportbot in https://github.com/nextcloud/server/pull/51437
[stable31] fix(encryption): Listen for user login and logout to set encryption key by @backportbot in https://github.com/nextcloud/server/pull/51311
[stable31] Allow to delete files without trashbin + add unit tests + some refactoring by @backportbot in https://github.com/nextcloud/server/pull/51397
[stable31] fix(dav): Fix share token pattern for base uri extraction by @backportbot in https://github.com/nextcloud/server/pull/51396
[stable31] fix(RichObjectStrings): Make exception messages for invalid parameters more useful for debugging by @backportbot in https://github.com/nextcloud/server/pull/51445
[stable31] test: Remove .only() calls by …
=> Update Nextcloud to 31.0.2

.github/spawn-dailies.sh, .github/workflows/test-daily.yml
Fix #3278 
- Enables dailies for Nextcloud 32
- Removees obsolte dailies url for Nextcloud 29
- Fixes tests for dailies of Nextcloud 30
- Adds tests for dailies for Nextcloud 31
~~Requires the tarball [`latest-stable31.tar.bz2`](https://download.nextcloud.com/server/daily/latest-stable32.tar.bz2) to be available! Already [requrested here](https://cloud.nextcloud.com/call/xs25tz5y#message_4447884), let's wait for an response.~~ --> Done!
=> Enable dailies for nextcloud 32
