nextcloud-snap/nextcloud-snap

parts/plugins/x-php.py, parts/plugins/x-redis.py, snapcraft.yaml, src/nextcloud/config.php, src/php/config/php.ini, src/redis/config/redis.conf, src/redis/scripts/start-redis-server
This PR resolves #2 by using redis for both the local and locking memcache. It runs via a unix socket only.
=> Use redis for local and locking memcache.

CHANGELOG, README.md, parts/plugins/x-apache.py, parts/plugins/x-php.py, parts/plugins/x-redis.py, snapcraft.yaml, src/nextcloud/apache_config, src/nextcloud/autoconfig.php, src/nextcloud/config.php, src/nextcloud/occ, src/nextcloud/setup_nextcloud, src/php/config/php-fpm.conf, src/php/config/php-fpm.d/www.conf, src/php/config/php.ini, src/php/scripts/start-php-fpm, src/redis/config/redis.conf, src/redis/scripts/start-redis-server
- Use redis for local and locking memcache.
- Use PHP FPM instead of PHP Apache module.
=> Release 9.0.50snap2

CHANGELOG, snapcraft.yaml
=> Update version to 9.0.50snap3.

snapcraft.yaml
=> Upgrade Nextcloud to 9.0.53.

CHANGELOG, README.md
- Upgrade Nextcloud to 9.0.53.
=> Release 9.0.53snap1

CHANGELOG, README.md, snapcraft.yaml
=> Update version number to 9.0.53snap2.

CHANGELOG, snapcraft.yaml
=> Update version number to 9.0.53snap3.

snapcraft.yaml
=> Update PHP to 7.0.11

snapcraft.yaml
This PR fixes #102 by upgrading the PHP used to 7.0.12.
=> Upgrade PHP to 7.0.12.

CHANGELOG, snapcraft.yaml
=> Update version to 10.0.1snap2.

README.md, snapcraft.yaml
Resolve #66 by adding the `removable-media` plug to the required apps.
=> Add ability to access removable media.

.travis.yml, .travis/deploy.sh
This uses daily-master for edge, and daily-stable10 for beta.
=> Use Travis cron jobs to spin off daily builds.

.travis.yml, .travis/cron.sh, .travis/deploy.sh, CHANGELOG, README.md, snapcraft.yaml
- Use Travis cron jobs to spin off daily builds.
- Add ability to access removable media.
=> Release 10.0.1snap3

.travis.yml, .travis/cron.sh, .travis/deploy.sh, CHANGELOG, README.md, snapcraft.yaml
Also update README and CHANGELOG, and revamp deployment a little.
=> Update version to 10.0.1snap3.

.travis.yml
=> CI: Re-enable strict host checking.

snapcraft.yaml
This PR resolves #135 by updating Nextcloud to 10.0.2.
=> Update Nextcloud to 10.0.2.

.travis/cron.sh, README.md, snapcraft.yaml
This PR resolves #143 by updating Nextcloud to v11.0.0. It also changes the daily beta to be stable11.
=> Update Nextcloud to v11.0.0.

snapcraft.yaml
This PR resolves #152 by updating the version of Apache used to v2.4.25.
=> Update Apache to v2.4.25.

snapcraft.yaml, src/php/config/php.ini
This PR resolves #154 by updating the version of PHP used in the snap to v7.1
=> Update PHP to 7.1

CHANGELOG, snapcraft.yaml
=> Update version to 11.0.0snap1.

src/https/certbot_nextcloud_plugin/webroot.py, src/https/scripts/renew-certs, src/https/scripts/restart-apache
This PR tries to _actually_ fix #159. Also restart apache if the certificates are renewed.
=> https: add 'map' parameter back to certbot plugin.

CHANGELOG, snapcraft.yaml, src/https/certbot_nextcloud_plugin/webroot.py, src/https/scripts/renew-certs, src/https/scripts/restart-apache, src/https/setup.py
- https: add 'map' parameter back to certbot plugin.
=> Release 11.0.0snap2

CHANGELOG, snapcraft.yaml
=> Update version to 11.0.0snap2.

CHANGELOG, snapcraft.yaml
- dailies: fix overly-fragile version regex.
=> Release 11.0.0snap3

CHANGELOG, snapcraft.yaml
=> Update version to 11.0.0snap3.

snapcraft.yaml
=> Added mysqldump command

snapcraft.yaml
This PR resolves #177 by upgrading Nextcloud to v11.0.1.
=> nextcloud: upgrade to 11.0.1.

README.md, snapcraft.yaml, src/php/config/php.ini
This PR resolves #173 by upgrading PHP from 7.0.12 to 7.1.1.
=> php: upgrade to 7.1.1.

snapcraft.yaml
This PR resolves #95 by upgrading redis to 3.2.6.
=> redis: upgrade to 3.2.6.

CHANGELOG, README.md, snapcraft.yaml
=> Update version to 11.0.1snap1.

README.md, parts/plugins/x-php.py, snapcraft.yaml, src/php/config/php.ini
This PR fixes #194 by using PHP v7.0.15 instead of v7.1.1.
=> php: downgrade to 7.0.15.

CHANGELOG, README.md, parts/plugins/x-php.py, snapcraft.yaml, src/php/config/php.ini
=> Release 11.0.1snap2

CHANGELOG, snapcraft.yaml
=> Update version to 11.0.1snap2.

CHANGELOG, README.md, snapcraft.yaml
=> Update version to 11.0.1snap3.

README.md, snap/snapcraft.yaml
This PR resolves #211 by updating Nextcloud to v11.0.2.
=> nextcloud: update to 11.0.2.

CHANGELOG, snap/snapcraft.yaml
=> Update version to 11.0.2snap1.

CHANGELOG, snap/snapcraft.yaml, src/mysql/start_mysql, src/nextcloud/scripts/setup_nextcloud
- mysql: fix socket location in root.ini.
=> Release 11.0.2snap2

snap/snapcraft.yaml
This PR fixes #241 by upgrading PHP from 7.0.15 to 7.0.18.
=> php: upgrade to 7.0.18.

CHANGELOG, README.md, snap/snapcraft.yaml
- php: upgrade to 7.0.18
- CI: make daily builds use snap/snapcraft.yaml
=> Release 11.0.2snap3

CHANGELOG, README.md, snap/snapcraft.yaml
=> Update version to 11.0.2snap3.

snap/snapcraft.yaml
This PR resolves #247 by using the digests provided by the various upstreams along with Snapcraft's `source-checksum` property.
=> yaml: verify integrity of components.

README.md, snap/snapcraft.yaml
This PR resolves #246 by upgrading Nextcloud to v11.0.3.
=> nextcloud: upgrade to 11.0.3.

.travis/cron.sh, CHANGELOG, README.md, snap/snapcraft.yaml, src/apache/conf/httpd.conf, src/apache/conf/ssl.conf
- apache: disable HTTP methods TRACE and TRACK
- nextcloud: upgrade to 11.0.3
- yaml: verify integrity of components
=> Release 11.0.3snap1

CHANGELOG, snap/snapcraft.yaml
=> Update version to 11.0.3snap1

CHANGELOG, snap/snapcraft.yaml
=> Update version to 11.0.3snap2

CHANGELOG, snap/snapcraft.yaml
=> Update version to 11.0.3snap3

CHANGELOG, snap/snapcraft.yaml
=> Update version to 11.0.3snap4

snap/snapcraft.yaml
=> Update PHP to 7.0.20

CHANGELOG, snap/snapcraft.yaml
=> Update version to 11.0.3snap5

.circleci/config.yml, .gitignore, .travis/cron.sh, CHANGELOG, snap/snapcraft.yaml, src/apache/conf/httpd.conf
- mdns-publisher: use godeps to manage dependencies
- apache: update to 2.4.26
=> Release 11.0.3snap6

CHANGELOG, snap/snapcraft.yaml
=> Update version to 11.0.3snap6

CHANGELOG, snap/snapcraft.yaml
=> Update version to 11.0.3snap7

CHANGELOG, snap/snapcraft.yaml
- php: update to 7.0.21
- apache: update to 2.4.27
=> Release 11.0.3snap7

CHANGELOG, README.md, snap/snapcraft.yaml
=> Update version to 11.0.4snap1

CHANGELOG, README.md, snap/snapcraft.yaml
- php: update to 7.0.22
- nextcloud: update to 11.0.4
- snapcraft.yaml: update summary
=> Release 11.0.4snap1

snap/snapcraft.yaml
This PR resolves #358 by updating PHP to v2.0.23.
=> php: update to v7.0.23

CHANGELOG, README.md, snap/snapcraft.yaml
=> Update version to 11.0.5snap1

CHANGELOG, snap/snapcraft.yaml
=> Update version to 11.0.5snap2

snap/snapcraft.yaml
This PR fixes #385 by updating from PHP v7.0.23 to v7.0.25.
=> php: update to 7.0.25

CHANGELOG, README.md, snap/snapcraft.yaml
=> Update version to 12.0.4snap1

CHANGELOG, README.md, snap/snapcraft.yaml
Please test this PR using the `11/candidate` channel:
$ sudo snap install nextcloud --channel=11/candidate
Or if you already have the snap installed:
$ sudo snap refresh nextcloud --channel=11/candidate
=> [11] Update version to 11.0.6snap1

README.md, snap/snapcraft.yaml, src/php/config/php.ini
=> php: update to 7.1.13

src/apache/conf/ssl.conf
=> apache: remove extra semicolon from hsts header

CHANGELOG, snap/snapcraft.yaml
=> Update version to 12.0.4snap2

snap/snapcraft.yaml
This PR resolves #431 by updating Nextcloud to v12.0.5.
=> nextcloud: update to 12.0.5

CHANGELOG, README.md, snap/snapcraft.yaml
=> Release 12.0.5snap1

.circleci/config.yml, .travis/cron.sh
This PR resolves #458 by building a daily v13 snap. It also adds v13 to the list of daily snaps that are tested on a daily basis.
=> CI: build daily v13 snaps

snap/snapcraft.yaml
This PR resolves #465  by updating PHP to 7.1.15.
=> PHP: Update to 7.1.15

CHANGELOG, snap/snapcraft.yaml
=> Update version to 12.0.5snap2

snap/snapcraft.yaml
This PR resolves #477 by updating Apache to the latest version.
=> apache: update to 2.4.29

src/nextcloud/scripts/occ
Without this we end up in this issue:
- https://github.com/nextcloud/server/issues/4291
=> occ: add apices and use  use $@ to pass arguments

README.md, snap/snapcraft.yaml, src/php/config/php.ini
This PR resolves #465 for the 11 track. Please test this PR using the `11/beta/pr-473` channel:
$ sudo snap install nextcloud --channel=11/beta/pr-473
Or, if you already have it installed (only do this if you're running the v11 snap):
$ sudo snap refresh nextcloud --channel=11/beta/pr-473
=> [11] php: update to 7.1.15

src/nextcloud/scripts/occ
=> [11] occ: add apices and use $@ to pass arguments

snap/snapcraft.yaml
=> Update PHP to 7.1.16

snap/snapcraft.yaml
This PR is a backport of #519, fixing #507 for v11.
=> [11] php: update to 7.1.16

CHANGELOG, README.md, snap/snapcraft.yaml
=> Update version to 12.0.5snap3

snap/snapcraft.yaml
Didn't tested it locally since this is only a security update. Fixes #537.
=> Update PHP version to 7.1.17

snap/snapcraft.yaml
=> nextcloud: update to 12.0.7

README.md, snap/snapcraft.yaml
Resolve #552 by updating Nextcloud to the final supported v11 release.
=> [11] nextcloud: update to 11.0.8

.circleci/config.yml, .travis/cron.sh
This PR resolves #559 by disabling v11 daily builds as well as tests.
=> Disable v11 daily builds and tests

.circleci/config.yml, src/apache/bin/httpd-wrapper, src/apache/bin/run-httpd, src/apache/utilities/apache-utilities, src/delay-on-failure/bin/delay-on-failure, src/hooks/bin/configure, src/hooks/utilities/hook-utilities, src/https/bin/disable-https, src/https/bin/enable-https, src/https/bin/renew-certs, src/https/bin/restart-apache, src/https/utilities/https-utilities, src/mysql/bin/start_mysql, src/mysql/support-files/mysql.server, src/mysql/utilities/mysql-utilities, src/nextcloud/bin/manual-install, src/nextcloud/bin/nextcloud-cron, src/nextcloud/bin/occ, src/nextcloud/bin/setup_nextcloud, src/nextcloud/utilities/nextcloud-utilities, src/php/bin/run-php, src/php/bin/start-php-fpm, src/php/utilities/php-utilities, src/redis/bin/start-redis-server, src/redis/utilities/redis-utilities, tests/static.sh
This PR resolves #561 by adding a static test that runs shellcheck on all shell scripts in the src/ directory, and fixing them all to pass.
=> many: implement static checks

snap/snapcraft.yaml, src/mysql/support-files/mysql.server, src/patches/support-compile-time-disabling-of-setpriority.patch
This PR changes the repository from where mysql-server is pulled and adds kyrofa's patch to make it run in heavily confined systems like Ubuntu Core.
It also updates mysql to 5.7.22
This tries to solve #329
=> Use a patch for mysql-server instead of kyrofa's custom repository

.circleci/config.yml, src/apache/bin/httpd-wrapper, src/apache/bin/run-httpd, src/apache/utilities/apache-utilities, src/delay-on-failure/bin/delay-on-failure, src/hooks/bin/configure, src/hooks/utilities/hook-utilities, src/https/bin/disable-https, src/https/bin/enable-https, src/https/bin/renew-certs, src/https/bin/restart-apache, src/https/utilities/https-utilities, src/mysql/bin/start_mysql, src/mysql/support-files/mysql.server, src/mysql/utilities/mysql-utilities, src/nextcloud/bin/manual-install, src/nextcloud/bin/nextcloud-cron, src/nextcloud/bin/occ, src/nextcloud/bin/setup_nextcloud, src/nextcloud/utilities/nextcloud-utilities, src/php/bin/run-php, src/php/bin/start-php-fpm, src/php/utilities/php-utilities, src/redis/bin/start-redis-server, src/redis/utilities/redis-utilities, tests/static.sh
This PR is a backport of #563, resolving #561 for v12.
=> [12] many: implement static checks

README.md, snap/snapcraft.yaml, src/hooks/bin/configure, src/nextcloud/bin/nextcloud-cron, src/nextcloud/utilities/nextcloud-utilities
=> Make Cronjob interval adjustable

snap/snapcraft.yaml
=> Nextcloud: update to 13.0.4

CHANGELOG, README.md, snap/snapcraft.yaml
=> Update version to 13.0.4snap1

snap/snapcraft.yaml
This PR resolves #643 by updating Apache to 2.4.34.
=> apache: update to 2.4.34

snap/snapcraft.yaml
This PR resolves #652 by updating PHP to v7.1.20.
=> php: update to 7.1.20

snap/snapcraft.yaml
This PR is a backport of #653, resolving #652 for v12.
=> [12] php: update to 7.1.20

snap/snapcraft.yaml
This PR resolves #645 by updating Nextcloud v12.0.10.
=> [12] nextcloud: update to 12.0.10

snap/snapcraft.yaml
This PR resolves #644 by updating Nextcloud v13.0.5.
=> nextcloud: update to 13.0.5

CHANGELOG, README.md, snap/snapcraft.yaml
- php: update to 7.1.20
- nextcloud: update to 13.0.5
- apache: update to 2.4.34
- php: enable FTP support
=> Release 13.0.5snap1

CHANGELOG, README.md, snap/snapcraft.yaml
=> Update version to 13.0.5snap1

snap/snapcraft.yaml
=> nextcloud: update to 13.0.6

snap/snapcraft.yaml
This PR resolves #715 by updating Nextcloud to v12.0.11.
=> [12] nextcloud: update to 12.0.11

snap/snapcraft.yaml
=> apache: update to 2.4.35

snap/snapcraft.yaml
=> nextcloud: update to 13.0.7

.circleci/config.yml, snap/snapcraft.yaml
This PR resolves #762 by updating Apache to the latest stable release.
=> apache: update to 2.4.37

.circleci/config.yml, snap/snapcraft.yaml
This PR is a backport of #739, #758, and #763, fixing #762 for v12.
=> [12] apache: update to 2.4.37

README.md, snap/snapcraft.yaml
This PR resolves #770 by updating v12 to the latest stable version: 12.0.12.
=> [12] nextcloud: update to v12.0.12

snap/snapcraft.yaml
=> php: update to 7.1.25

.circleci/runtests.sh
This PR is a backport of #828, resolving #827 for v12.
=> [12] ci: update rubygems for tests

snap/snapcraft.yaml
This PR is a backport of #810, fixing #808 for v12.
=> [12] php: update to 7.1.25

snap/snapcraft.yaml
This PR resolves #795 by updating v12 to the last supported release of v12.
=> [12] nextcloud: update to 12.0.13

CHANGELOG, README.md, snap/snapcraft.yaml
=> Update version to 12.0.13snap1

snap/snapcraft.yaml, src/apache/bin/run-httpd, src/nextcloud/bin/nextcloud-fixer, src/nextcloud/bin/setup-nextcloud, src/php/utilities/php-utilities
This PR resolves #706 by updating Nextcloud to v14.0.5.
Please test this PR using the `beta/pr-799` channel:
$ sudo snap install nextcloud --channel=beta/pr-799
$ sudo snap refresh nextcloud --channel=beta/pr-799
=> nextcloud: update to 14.0.5

snap/snapcraft.yaml
This PR resolves #846 by updating Nextcloud to v13.0.10.
=> [13] nextcloud: update to 13.0.10

CHANGELOG, README.md
=> CHANGELOG: update for 13.0.10snap1

snap/snapcraft.yaml
This PR resolves #848 by updating Nextcloud to v14.0.6.
=> nextcloud: update to 14.0.6

snap/snapcraft.yaml, src/php/config/php.ini, tests/spec/change_mode_spec.rb
Now that we are on Nextcloud 14 we can start to test this.
This PR resolves #617
=> Update PHP to the latest 7.2 release

CHANGELOG, README.md, snap/plugins/x-php.py, snap/snapcraft.yaml, src/php/config/php.ini, tests/spec/change_mode_spec.rb
- php: enable large file support on 32-bit systems
- nextcloud: update to 14.0.6
- php: update to 7.2.14
Please test this PR using the `candidate` channel:
$ sudo snap install --candidate nextcloud
$ sudo snap refresh --candidate nextcloud
=> Release 14.0.6snap1

snap/snapcraft.yaml
This PR resolves #869 by updating Apache to the latest stable release.
=> apache: update to 2.4.38

CHANGELOG, src/nextcloud/bin/nextcloud-fixer
- nextcloud-fixer: disable theming app on new installs
=> Release 15.0.2snap2

snap/snapcraft.yaml
=> [14] apache: update to 2.4.38

snap/snapcraft.yaml
=> [13] apache: update to 2.4.38

CHANGELOG, README.md, snap/snapcraft.yaml
=> Release 15.0.4snap1

snap/snapcraft.yaml
=> [14] nextcloud: update to 14.0.7

snap/snapcraft.yaml
=> [13] nextcloud: update to 13.0.11

snap/snapcraft.yaml
This PR resolves #916 by updating Nextcloud to the latest v15 release.
=> nextcloud: update to 15.0.5

snap/snapcraft.yaml
Resolves #911 by updating to MySQL Server 5.7.25.
=> MySQL: Update to 5.7.25

snap/snapcraft.yaml
=> Redis: Update to 4.0.13

snap/snapcraft.yaml
This PR resolves #925 by updating PHP to the latest 7.2 release.
=> php: update to 7.2.16

snap/snapcraft.yaml
This PR resolves #924 by updating PHP to the latest 7.1 release.
=> php: update to 7.1.27

snap/snapcraft.yaml
=> php: update to 7.2.17

snap/snapcraft.yaml
=> nextcloud: update to 15.0.7

CHANGELOG, README.md, snap/snapcraft.yaml
- nextcloud: update to 15.0.7
- php: update to 7.2.17
- apache: update to 2.4.39
=> Release 15.0.7snap1

snap/snapcraft.yaml
=> update: mysql to 5.7.26

snap/snapcraft.yaml
This PR resolves #982 by updating PHP to the latest 7.2 release.
=> php: update to 7.2.18

CHANGELOG, README.md
=> CHANGELOG: update for 13.0.12snap1

snap/snapcraft.yaml
This PR is a backport of #953, resolving #952 for v14.
=> apache: update to 2.4.39

CHANGELOG, README.md
=> CHANGELOG: update for 14.0.10snap1

.travis/cron.sh
This PR resolves #998 by enabling daily v16 builds.
=> ci: enable daily v16

CHANGELOG, src/https/certbot_nextcloud_plugin/webroot.py, src/https/setup.py
- certbot: re-introduce custom webroot plugin
=> Release 15.0.8snap2

snap/snapcraft.yaml
=> Update PHP to 7.2.19

CHANGELOG, snap/snapcraft.yaml
=> Release 15.0.8snap3

snap/snapcraft.yaml
This PR resolves #1059 by updating Nextcloud to the latest v15 release.
=> nextcloud: update to 15.0.10

.github/ISSUE_TEMPLATE/bug_report.md, CHANGELOG, README.md, snap/snapcraft.yaml
- nextcloud: update to 15.0.10
=> Release 15.0.10snap1

snap/snapcraft.yaml
This PR resolves #1068 by updating MySQL to the latest 5.7 release.
=> mysql: update to 5.7.27

snap/snapcraft.yaml
This PR resolves #1072 by updating PHP to the latest 7.2 release.
=> php: update to 7.2.20

CHANGELOG, snap/snapcraft.yaml
- php: update to 7.2.20
- mysql: update to 5.7.27
=> Release 15.0.10snap2

snap/snapcraft.yaml
This PR resolves #1081 by updating PHP to the latest 7.2 release.
=> php: update to 7.2.21

.github/FUNDING.yml, CHANGELOG, snap/snapcraft.yaml, src/mysql/bin/start_mysql, src/mysql/my.cnf
- php: update to 7.2.21
- mysql: explicitly configure error log file name
- mysql: only write root password to root.ini if successfully set
=> Release 15.0.10snap3

snap/snapcraft.yaml
This PR resolves #1091 by updating Apache to the latest 2.4 release.
=> apache: update to 2.4.41

snap/snapcraft.yaml
This PR resolves #1095 by updating Nextcloud to the latest v15 release.
=> nextcloud: update to 15.0.11

snap/snapcraft.yaml
This PR resolves #1110 by updating PHP to the latest 7.2 release.
=> php: update to 7.2.22

CHANGELOG, README.md, snap/snapcraft.yaml
=> Release 16.0.5snap1

snap/snapcraft.yaml
This PR resolves #1133 by updating PHP to the latest 7.2 release.
=> php: update to 7.2.23

.circleci/config.yml, .travis/cron.sh, CHANGELOG, snap/snapcraft.yaml, src/common/utilities/common-utilities, src/import-export/bin/import-data, src/nextcloud/bin/occ, src/php/config/php.ini, src/php/utilities/php-utilities, tests/spec/maintenance_mode_spec.rb, tests/spec/spec_helper.rb
- php: update to 7.2.23
- php: check file timestamps for opcache
- tests: disable v14 dailies and enable v16
=> Release 16.0.5snap2

snap/snapcraft.yaml
This PR resolves #1143 by updating MySQL to the latest 5.7 release.
=> mysql: update to 5.7.28

snap/snapcraft.yaml
This is a backport of #1153, resolving #1152 for v15.
=> php: update to 7.2.24

CHANGELOG, snap/snapcraft.yaml
- php: update to 7.2.24
- mysql: update to 5.7.28
=> Release 16.0.5snap3

snap/snapcraft.yaml
This PR resolves #1156 by updating Nextcloud to the latest v15 release
=> nextcloud: update to 15.0.13

CHANGELOG, README.md
=> CHANGELOG: update for 15.0.13snap1

.circleci/config.yml, .travis/cron.sh
This PR resolves #1175 by building, releasing, and testing a snap daily from stable17.
=> ci: enable daily v17 snap

README.md, snap/snapcraft.yaml, src/php/config/php.ini, tests/spec/change_mode_spec.rb
This PR resolves #1149 by updating PHP to the latest v7.3 release.
=> php: update to 7.3.12

snap/snapcraft.yaml
=> php: update to 7.3.13

.circleci/config.yml, .travis/cron.sh, CHANGELOG, README.md, snap/snapcraft.yaml, src/php/config/php.ini, tests/spec/change_mode_spec.rb
=> Release 16.0.5snap4

snap/snapcraft.yaml
This PR resolves #1209 by updating PHP to the latest 7.2 release.
=> php: update to 7.2.26

CHANGELOG, src/nextcloud/bin/nextcloud-fixer, src/nextcloud/fixes/existing-install/1_upgrade.sh, src/nextcloud/fixes/existing-install/2_update-apps.sh, src/nextcloud/fixes/existing-install/3_add-missing-indices.sh, src/nextcloud/fixes/existing-install/README, src/nextcloud/fixes/existing-install/maintenance/1_convert-filecache-bigint.sh, src/nextcloud/fixes/existing-install/maintenance/README, src/nextcloud/fixes/fresh-install/1_disable-theming.sh, src/nextcloud/fixes/fresh-install/2_add-missing-indices.sh, src/nextcloud/fixes/fresh-install/3_convert-filecache-bigint.sh, src/nextcloud/fixes/fresh-install/README
- nextcloud-fixer: upgrade and update apps before anything else
=> Release 16.0.7snap2

snap/snapcraft.yaml
This PR resolves #1217 by updating MySQL to the latest 5.7 release.
=> mysql: update to 5.7.29

snap/snapcraft.yaml
This PR resolves #1211 by updating Nextcloud to the latest v15 release.
=> nextcloud: update to 15.0.14

.circleci/config.yml, .travis/cron.sh
This PR resolves #1225 by enabling v18 dailies.
=> Enable daily release and test of v18

CHANGELOG, README.md
=> CHANGELOG: update for 15.0.14snap1

.circleci/config.yml, snap/snapcraft.yaml
This PR resolves #1230 by updating PHP to the latest 7.3 release.
=> php: update to 7.3.14

.circleci/config.yml, .github/FUNDING.yml, .travis/cron.sh, CHANGELOG, README.md, snap/snapcraft.yaml, src/common/utilities/common-utilities, src/hooks/bin/pre-refresh, src/nextcloud/fixes/existing-install/99_notify_admins.sh, src/nextcloud/fixes/fresh-install/99_record_snap_version.sh, src/nextcloud/utilities/nextcloud-utilities
- nextcloud: update to 16.0.8
- hooks: add pre-refresh hook to update apps
- php: update to 7.3.14
- nextcloud: notify admins upon update
- mysql: update to 5.7.29
=> Release 16.0.8snap1

.circleci/config.yml, .travis/cron.sh
=> Disable v15 dailies

CHANGELOG, README.md, snap/snapcraft.yaml, src/nextcloud/utilities/nextcloud-utilities
- redis: update phpredis to 5.1.1 and redis to 5.0.7
- nextcloud: support notifying users with spaces in username
- php: update to 7.3.15
- nextcloud: update to 17.0.3
=> Release 17.0.3snap1

CHANGELOG, README.md
=> CHANGELOG: update for 16.0.8snap2

snap/snapcraft.yaml
This PR resolves #1301 by updating PHP to the latest v7.3 release.
=> php: update to 7.3.17

CHANGELOG, README.md, snap/snapcraft.yaml
- nextcloud: update to 18.0.4
- php: update to 7.3.17
- apache: update to 2.4.43
=> Release 18.0.4snap1

CHANGELOG, README.md
=> CHANGELOG: update for 17.0.6snap1

snap/snapcraft.yaml
This PR resolves #1320 by updating MySQL to the latest 5.7 release.
=> mysql: update to 5.7.30

snap/snapcraft.yaml
This PR resolves #1336 by updating PHP to the latest v7.3 release.
=> php: update to 7.3.18

.circleci/config.yml, CHANGELOG, snap/snapcraft.yaml, tests/spec/spec_helper.rb
- php: update to 7.3.18
- mysql: update to 5.7.30
=> Release 18.0.4snap2

.circleci/Dockerfile, .circleci/config.yml, CHANGELOG, snap/plugins/x-apache.py, snap/snapcraft.yaml, src/mysql/bin/run-mysqldump
=> Release 18.0.4snap4

.circleci/config.yml, tests/spec/spec_helper.rb
This is a backport of #1343 for v17.
=> tests: update CircleCI image

CHANGELOG, README.md
=> CHANGELOG: update for 16.0.11snap1

snap/plugins/apache.py, snap/plugins/php.py, snap/plugins/redis.py
This PR is a backport of #1376 for v17.
=> snap: rewrite plugins to workaround snapcraft breakage

.circleci/Dockerfile, .circleci/config.yml, snap/plugins/apache.py, snap/snapcraft.yaml, src/mysql/bin/run-mysqldump
This PR is a backport of #1250, resolving #755 for v17.
=> base: core18

.circleci/config.yml, .travis/cron.sh
This PR resolves #1369 by creating, testing, and releasing a snap of stable19 daily.
=> tests: enable v19 dailies

.circleci/Dockerfile, snap/snapcraft.yaml
This PR resolves #1399 by updating PHP to the latest 7.3 release.
=> php: update to 7.3.20

snap/snapcraft.yaml
This PR resolves #1404 by updating MySQL to the latest 5.7 release.
=> mysql: update to 5.7.31

CHANGELOG, src/mysql/bin/start_mysql, src/mysql/support-files/mysql.server
- mysql: ignore config files on host
=> Release 19.0.1snap2

snap/snapcraft.yaml
This PR resolves #1430 by updating Apache to the latest 2.4 release.
=> apache: update to 2.4.46

snap/snapcraft.yaml
This PR resolves #1428 by updating PHP to the latest 7.3 release.
=> php: update to 7.3.21

CHANGELOG, snap/snapcraft.yaml
- php: update to 7.3.21
- apache: update to 2.4.46
=> Release 19.0.1snap3

CHANGELOG, README.md, snap/snapcraft.yaml
=> Release 19.0.2snap1

CHANGELOG, README.md, snap/snapcraft.yaml
- snapcraft.yaml: enable network monitoring
- nextcloud: update to 19.0.3
=> Release 19.0.3snap1

snap/snapcraft.yaml
This PR resolves #1469 by updating PHP to the latest v7.3 release.
=> php: update to 7.3.23

CHANGELOG, snap/snapcraft.yaml, src/php/config/php.ini
- php: disable output buffering
- php: update to 7.3.23
- php: include support for argon2
=> Release 19.0.3snap2

snap/snapcraft.yaml
This PR resolves #1501 by updating Nextcloud to the latest v17 release.
=> nextcloud: update to 17.0.10

snap/snapcraft.yaml, src/mysql/bin/reload-mysql, src/mysql/bin/run-mysql, src/mysql/bin/run-mysqldump, src/mysql/bin/start_mysql
This PR resolves #1510 by updating MySQL to the latest 5.7 release.
=> mysql: update to 5.7.32

CHANGELOG, README.md
=> CHANGELOG: update for 17.0.10snap1

CHANGELOG, README.md, snap/snapcraft.yaml, src/nextcloud/utilities/nextcloud-utilities, tests/spec/change_php_memory_limit_spec.rb, tests/spec/enable_https_spec.rb, tests/spec/import_export_spec.rb, tests/spec/login_spec.rb
- nextcloud: workaround invalid json from occ
- nextcloud: update to 20.0.1
=> Release 20.0.1snap1

snap/snapcraft.yaml
This PR resolves #1550 by updating PHP to the latest v7.4 release.
=> php: update to 7.4.13

.circleci/config.yml, CHANGELOG, README.md, snap/snapcraft.yaml, src/php/bin/reload-php, tests/spec/change_php_memory_limit_spec.rb, tests/spec/enable_https_spec.rb, tests/spec/import_export_spec.rb, tests/spec/login_spec.rb
- php: update to 7.4.13
- nextcloud: update to 20.0.2
- php: fix shebang in reload-php
=> Release 20.0.2snap1

src/php/bin/reload-php
This PR is a backport of #1544, fixing #1547 for v19.
=> php: fix shebang in reload-php

snap/snapcraft.yaml
This PR resolves #1559 by updating PHP to the latest v7.3 release.
=> php: update to 7.3.25

CHANGELOG, README.md
=> CHANGELOG: update for 19.0.5snap1

CHANGELOG, README.md
=> CHANGELOG: update for 18.0.11snap1

CHANGELOG, README.md, snap/snapcraft.yaml
=> Release 20.0.3snap1

CHANGELOG, README.md
=> CHANGELOG: update for 19.0.6snap1

CHANGELOG, README.md
=> CHANGELOG: update for 18.0.12snap1

snap/snapcraft.yaml
This PR resolves #1602 by updating PHP to the latest v7.4 release.
=> php: update to 7.4.14

CHANGELOG, snap/snapcraft.yaml
=> Release 20.0.4snap2

snap/snapcraft.yaml
This PR resolves #1616 by updating MySQL to the latest 5.7 release.
=> mysql: update to 5.7.33

CHANGELOG, README.md, snap/snapcraft.yaml
- nextcloud: update to 20.0.6
- mysql: update to 5.7.33
=> Release 20.0.6snap1

CHANGELOG, README.md, snap/snapcraft.yaml
=> Release 20.0.7snap1

snap/snapcraft.yaml
This PR resolves #1638 by updating PHP to the latest v7.4 release.
=> php: update to 7.4.15

snap/snapcraft.yaml
=> redis: update to 5.0.12

snap/snapcraft.yaml
=> Update NextCloud 20.0.9

snap/snapcraft.yaml
=> Upgrade MySQL to 5.7.34

snap/snapcraft.yaml
=> Update PHP 7.4.18

.circleci/config.yml, snap/snapcraft.yaml, src/mysql/bin/start_mysql, src/mysql/support-files/mysql.server
This PR resolves #1626 by upgrading MySQL to the latest v8 release, thus paving the path to Nextcloud v21, which requires this.
=> mysql: update to 8.0.24

.circleci/config.yml, CHANGELOG, README.md, snap/snapcraft.yaml, src/mysql/bin/start_mysql, src/mysql/support-files/mysql.server
- mysql: update to 8.0.24
- php: update to 7.4.18
=> Release 20.0.9snap2

README.md
Signed-off-by: szaimen <szaimen@e.mail.de>
=> Readme.md - Show correct php version

CHANGELOG, src/mysql/my.cnf
- mysql: disable binary logging
=> Release 21.0.1snap2

snap/snapcraft.yaml
=> Upgrade Apache 2.4.48

snap/snapcraft.yaml
=> Upgrade PHP 7.4.20

.circleci/Dockerfile
=> circleci: pin go to 1.15

snap/snapcraft.yaml
=> nextcloud: update to 19.0.12

src/mysql/my.cnf
Cherry-picked from master.
If this is OK, I will later backport the PHP & Apache updates too.
=> mysql: disable binary logging

.circleci/config.yml, .travis/cron.sh
Also disable v18, which is no longer supported.
=> ci: enable daily build and test of v21 latest

CHANGELOG, README.md
=> CHANGELOG: update for 19.0.12snap1

snap/snapcraft.yaml
=> Upgrade PHP to 7.4.21

snap/snapcraft.yaml
=> Nextcloud update to 20.0.11

snap/snapcraft.yaml
=> Upgrade Nextcloud 21.0.3

CHANGELOG, README.md
=> CHANGELOG: update for 20.0.11snap1

.circleci/config.yml, .travis/cron.sh, CHANGELOG, snap/snapcraft.yaml
- nextcloud: update to 21.0.3
- php: update to 7.4.21
- apache: update to 2.4.48
=> Release 21.0.3snap1

snap/snapcraft.yaml
=> Upgrade MySQL to 8.0.26

CHANGELOG, snap/snapcraft.yaml, src/nextcloud/bin/manual-install
- nextcloud: support specifying data directory in manual-install
- mysql: upgrade to 8.0.26
=> Release 21.0.3snap2

snap/snapcraft.yaml
=> [nextcloud] upgrade to 20.0.12

snap/snapcraft.yaml
=> [redis] upgrade to 6.0.15

snap/snapcraft.yaml
=> Upgrade Nextcloud to 21.0.4

snap/snapcraft.yaml
=> Upgrade PHP to 7.4.23

snap/snapcraft.yaml
=> Update Redis to 6.0.15

CHANGELOG, README.md, snap/snapcraft.yaml
- php: update to 7.4.23
- redis: update to 6.0.15
- nextcloud: update to 21.0.4
=> Release 21.0.4snap1

CHANGELOG, README.md
=> CHANGELOG: update for 20.0.12snap1

CHANGELOG, README.md, snap/snapcraft.yaml
=> Release 22.1.1snap1

snap/snapcraft.yaml
Fixes #1845
Fixes vulnerabilities
=> Upgrade Apache to 2.4.49

snap/snapcraft.yaml, src/php/config/php-fpm.conf, src/php/config/php-fpm.d/www.conf, src/php/config/php.ini, tests/integration/change_mode_spec.rb
This PR resolves #1654 by updating PHP to the latest v8 release.
=> php: update to 8.0.10

snap/snapcraft.yaml
=> Upgrade PHP 8.0.11

snap/snapcraft.yaml
Fixes #1865 
Posted on changelog site currently as latest release.
=> Upgrade Nextcloud to 22.2.0

snap/snapcraft.yaml
=> Upgrade Apache to 2.4.50

snap/snapcraft.yaml
=> upgrade nextcloud to 20.0.13

snap/snapcraft.yaml
=> upgrade nextcloud to 21.0.5

snap/snapcraft.yaml
=> upgrade nextcloud to 20.0.14

snap/snapcraft.yaml
This PR resolves #1930 by updating Nextcloud to the latest v21 release.
=> nextcloud: update to 21.0.7

.github/workflows/test-daily.yml
=> ci: test daily builds

snap/snapcraft.yaml
=> update php to 7.4.26

snap/snapcraft.yaml
=> Upgrade Apache to 2.4.52

.github/spawn-dailies.sh, .github/workflows/daily.yml, .github/workflows/stale.yml, .github/workflows/test-daily.yml, CHANGELOG, snap/snapcraft.yaml
=> Release 22.2.3snap2

snap/snapcraft.yaml
=> Upgrade MySQL 8.0.28

snap/snapcraft.yaml
=> Upgrade PHP to 8.0.15

.github/spawn-dailies.sh, .github/workflows/test-daily.yml, CHANGELOG, snap/snapcraft.yaml
- php: update to 8.0.15
- mysql: update to 8.0.28
=> Release 22.2.3snap3

snap/snapcraft.yaml
=> Upgrade NextCloud 22.2.5

snap/snapcraft.yaml
=> nextcloud: update to 21.0.9

snap/snapcraft.yaml
=> Upgrade PHP to 8.0.16

CHANGELOG
- php: update to 8.0.16
- nextcloud: update to 21.0.9
- mysql: update to 8.0.28
- apache: update to 2.4.52
=> CHANGELOG: update for 21.0.9snap1

CHANGELOG, snap/snapcraft.yaml
- php: update to 8.0.16
- nextcloud: update to 22.2.5
=> Release 22.2.5snap1

snap/snapcraft.yaml, tests/unit/common_utilities_spec.sh
=> Upgrade Nextcloud 23.0.2

CHANGELOG, README.md, snap/snapcraft.yaml, tests/unit/common_utilities_spec.sh
=> Release 23.0.2snap1

snap/snapcraft.yaml
=> nextcloud: update to 22.2.6

snap/snapcraft.yaml
Contains security fixes.
Fixes #2018
=> Upgrade Apache to 2.4.53

.github/workflows/test.yml, CHANGELOG, snap/snapcraft.yaml, tests/integration/spec_helper.rb
- apache: update to 2.4.53
- nextcloud: update to 23.0.3
=> Release 23.0.3snap1

.github/spawn-dailies.sh
[21 is now EOL](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule).
=> ci: disable 21 dailys

snap/snapcraft.yaml
=> Upgrade Nextcloud to 23.0.4

snap/snapcraft.yaml
=> update nextcloud to 22.2.6

snap/snapcraft.yaml
=> Upgrade Nextcloud to 23.0.5

snap/snapcraft.yaml
=> Update PHP to 8.0.19

snap/snapcraft.yaml
=> Nextcloud 24.0.1

snap/snapcraft.yaml
=> Upgrade PHP to 8.0.20

CHANGELOG, README.md, snap/snapcraft.yaml
- php: update to 8.0.20
- apache: update to 2.4.54
- nextcloud: update to 24.0.1
=> Release 24.0.1snap1

snap/snapcraft.yaml
=> Upgrade Apache httpd to 2.4.54

snap/snapcraft.yaml
=> php: update to 8.0.21

snap/snapcraft.yaml
=> Update Nextcloud to 24.0.3

.github/workflows/test.yml, CHANGELOG, snap/snapcraft.yaml
- php: update to 8.0.21
- nextcloud: update to 24.0.3
=> Release 24.0.3snap1

snap/snapcraft.yaml
=> Upgrade MySQL to 8.0.30

.github/spawn-dailies.sh
Disable 22 dailys and enable 23 & 24.
Fixes #2145
=> ci: disable 22 dailys, as it's EOL

.github/spawn-dailies.sh, CHANGELOG, snap/snapcraft.yaml
=> Release 24.0.3snap2

snap/snapcraft.yaml
=> Update Nextcloud to v24.0.4

snap/snapcraft.yaml
=> Upgrade PHP to 8.0.23

snap/snapcraft.yaml
Resolve https://github.com/nextcloud-snap/nextcloud-snap/issues/2149
=> nextcloud: update to 23.0.8

snap/snapcraft.yaml
=> nextcloud: update to 23.0.9

CHANGELOG, snap/snapcraft.yaml
=> Release 24.0.5snap1

snap/snapcraft.yaml
=> Upgrade PHP to 8.0.24

snap/snapcraft.yaml
=> Upgrade Nextcloud to 24.0.6

CHANGELOG, snap/snapcraft.yaml
- nextcloud: update to 24.0.6
- php: update to 8.0.24
=> Release 24.0.6snap1

CHANGELOG, snap/snapcraft.yaml
=> Release 24.0.6snap2

snap/snapcraft.yaml
=> Upgrade PHP to 8.0.25

snap/snapcraft.yaml
=> Upgrade Nextcloud to 24.0.7

snap/snapcraft.yaml
Also cherry-picked the upgrade to PHP 8.0.25.
=> Upgrade nextcloud to 23.0.11

CHANGELOG, snap/snapcraft.yaml
- nextcloud: update to 24.0.7
- php: update to 8.0.25
=> Release 24.0.7snap1

snap/snapcraft.yaml, src/mysql/support-files/mysql.server
This release includes more fixes than usual: https://github.com/nextcloud/server/milestone/208?closed=1
=> nextcloud: update to 24.0.8

snap/snapcraft.yaml, src/mysql/support-files/mysql.server
This is the latest public release for 23.0.x
=> nextcloud: upgrade to 23.0.12

README.md, snap/snapcraft.yaml
Fix #2211 
Fix #2222 
Don't want to attacked you @stondino00, just had the time for yet. Feel free to close this PR if not needed.
Anyways, not sure, if the tests success, as mentoined in [this comment](https://github.com/nextcloud-snap/nextcloud-snap/pull/2222#issuecomment-1302154488). No clue how fix them myself right now.
Also, not sure if it's right to change the changelog already here. Not sure what your process is for. Just a suggestion from my side.
=> nextcloud: update to 25.0.2

CHANGELOG, README.md, snap/snapcraft.yaml
=> Release 25.0.2snap1

snap/snapcraft.yaml
=> Upgrade PHP to 8.0.27

snap/snapcraft.yaml
=> Update MySQL to 8.0.32

snap/snapcraft.yaml
=> Upgrade HTTP to 2.4.55

snap/snapcraft.yaml
=> Update Nextcloud to 25.0.3

snap/snapcraft.yaml
=> nexcloud: update to 24.0.9

CHANGELOG, snap/snapcraft.yaml
- apache: update to 2.4.55
- nextcloud: update to 25.0.3
- mysql: update to 8.0.32
- php: update to 8.0.27
=> Release 25.0.3snap1

snap/snapcraft.yaml
=> Upgrade Redis to 6.2.10

snap/snapcraft.yaml
=> Upgrade PHP to 8.0.28

snap/snapcraft.yaml, src/php/config/php-fpm.d/www.conf, src/php/config/php.ini, tests/integration/change_mode_spec.rb
This PR resolves #2259 by updating PHP to the latest 8.1 release.
=> php: update to 8.1.16

.github/spawn-dailies.sh, .github/workflows/test-daily.yml, CHANGELOG, snap/snapcraft.yaml, src/php/config/php-fpm.d/www.conf, src/php/config/php.ini, tests/integration/change_mode_spec.rb
=> Release 25.0.3snap3

snap/snapcraft.yaml
=> Upgrade Nextcloud to 25.0.4

snap/snapcraft.yaml
=> Upgrade Redis to 6.2.11

snap/snapcraft.yaml
=> Upgrade Apache HTTP to 2.4.56

snap/snapcraft.yaml
=> Upgrade Nextcloud to 25.0.5

.github/spawn-dailies.sh, .github/workflows/test-daily.yml, CHANGELOG, snap/snapcraft.yaml
=> Release 25.0.5snap1

CHANGELOG, snap/snapcraft.yaml
=> Release 25.0.5snap2

snap/snapcraft.yaml
=> apache: update to 2.4.57

snap/snapcraft.yaml
=> Upgrade Redis to 6.2.12

snap/snapcraft.yaml
=> Upgrade Nextcloud to 25.0.6

snap/snapcraft.yaml
=> Upgrade MySQL to 8.0.33

snap/snapcraft.yaml
=> nextcloud: update to 24.0.12

snap/snapcraft.yaml
=> Upgrade Nextcloud to 25.0.7

snap/snapcraft.yaml
=> Upgrade PHP to 8.1.19

snap/snapcraft.yaml
=> Upgrade PHP to 8.1.20

CHANGELOG, snap/snapcraft.yaml, src/https/utilities/https-utilities
- php: update to 8.1.20
- certbot: use most recent certs
- nextcloud: update to 25.0.7
=> Release 25.0.7snap1

README.md, snap/snapcraft.yaml
Fixes #2391 
An early PR as discussed in linked issue.
I probably missed something, just tell me then.
=> Upgrade Nextcloud to 26.0.2

snap/snapcraft.yaml
Fix #2365
If you don't like the new module, just close this PR. ;)
=> php: add config flag --enable-sysvsem

snap/snapcraft.yaml
=> nextcloud: update to 26.0.3

CHANGELOG, README.md, snap/snapcraft.yaml, src/import-export/bin/import-data
- import: add documentation about confinement
- php: add config flag --enable-sysvsem
- nextcloud: update to 26.0.2
=> Release 26.0.2snap1

snap/snapcraft.yaml
=> nextcloud: update to 25.0.8

README.md, snap/snapcraft.yaml
Removes all mdns references to solve the actual build error and fixes #2443.
Sqash and merge because I'm a pig!
=> Remove mdns

README.md, snap/snapcraft.yaml
Also remove mentions of mDNS in README
=> snapcraft.yaml: remove mdns-publisher

snap/snapcraft.yaml
=> Upgrade Redis to 6.2.13

snap/snapcraft.yaml
=> Update: MySQL to 8.0.34

snap/snapcraft.yaml
=> Update: Nextcloud to 26.0.4

CHANGELOG
- nextcloud: update to 25.0.8
- mdns-publisher: remove from the snap
=> Release 25.0.8snap1

README.md, snap/snapcraft.yaml
Fix #2466 
To be done before merging:
=> nextcloud: update to 27.0.1

snap/snapcraft.yaml
=> Upgrade PHP to 8.1.22

snap/snapcraft.yaml
=> nextcloud: update to 27.0.2

CHANGELOG
Have been running this for a week now on my production instance.
=> Release 25.0.9snap1

snap/snapcraft.yaml
=> nextcloud: update to 26.0.5

snap/snapcraft.yaml
=> nextcloud: update to 25.0.10

snap/snapcraft.yaml
=> Update Nextcloud to 27.1.0

snap/snapcraft.yaml
=> nextcloud: update to 25.0.11

snap/snapcraft.yaml
=> nextcloud: update to 26.0.6

snap/snapcraft.yaml
=> Update Nextcloud to 27.1.1

.github/workflows/test.yml
Is this the only change that is needed @kyrofa ?
=> CI: upload snap artifact

snap/snapcraft.yaml
=> nextcloud: update to 27.1.2

snap/snapcraft.yaml
=> Upgrade Apache to 2.4.58

snap/snapcraft.yaml
=> Upgraded Redis to 6.2.14

snap/snapcraft.yaml
=> Upgrade Nextcloud to 27.1.3

snap/snapcraft.yaml
=> Upgrade PHP to 8.1.25

snap/snapcraft.yaml
=> Upgrade Nextcloud to 27.1.4

snap/snapcraft.yaml
Fixes https://github.com/nextcloud-snap/nextcloud-snap/issues/2618
=> nextcloud: update to 26.0.9

.github/spawn-dailies.sh, CHANGELOG, snap/snapcraft.yaml
Fix #2616 
27.1.5 comming in a week, so maybe we should release this before. It's long enough in beta anyway imo. :)
=> Release 27.1.4snap1

snap/snapcraft.yaml
=> nextcloud: update to 26.0.10

snap/snapcraft.yaml
=> Upgrade MySQL to 8.0.36

snap/snapcraft.yaml, src/php/config/php-fpm.conf, src/php/config/php-fpm.d/www.conf, src/php/config/php.ini, tests/integration/change_mode_spec.rb
This PR resolves #2564 by upgrading PHP to the latest v8.2 release.
=> php: update to 8.2.15

snap/snapcraft.yaml
=> Upgrade Nextcloud to 28.0.2

snap/snapcraft.yaml
=> nextcloud: update to 26.0.11

README.md
Fix some typos, info, and make the section for configuring notify_push as brief as possible, as the proper instructions are on the wiki.
=> Fix some README.md problems

snap/snapcraft.yaml
Also lift the phpredis extension to version 6.0.2
=> redis: upgrade to 7.0.15

snap/snapcraft.yaml
=> Update Nextcloud to 28.0.3

snap/snapcraft.yaml
=> nextcloud: update to 27.1.7

CHANGELOG, README.md
Also update README.md with current versions
=> Release 27.1.7snap1

snap/snapcraft.yaml
=> Upgrade Nextcloud to 28.0.4

snap/snapcraft.yaml
=> Upgrade Apache to 2.4.59

snap/snapcraft.yaml
=> Upgrade PHP to 8.2.18

snap/snapcraft.yaml
=> Update Nextcloud to 28.0.5

snap/snapcraft.yaml
=> nextcloud: update to 27.1.9

snap/snapcraft.yaml
=> Update Nextcloud to 28.0.6

.github/spawn-dailies.sh, .github/workflows/test-daily.yml, CHANGELOG, README.md, snap/snapcraft.yaml, src/nextcloud/config/config.php, src/nextcloud/fixes/existing-install/7_add_maintenance_window.sh
Fix #2641 
Fix #2748
Fix #2737
Fix #2658
Fix #2734
=> Release 28.0.6snap1

snap/snapcraft.yaml
=> Update Nextcloud to 29.0.1

snap/snapcraft.yaml
=> nextcloud: update to 27.0.10

README.md
=> Update README.md to Nextcloud 28

snap/snapcraft.yaml
=> Update Nextcloud to 29.0.2

README.md
I recently did a PR to update the README.md to Nextcloud 28.
But the develop branch now has since then been updated to Nextcloud 29.
So now the README.md needs adjusting a second time to reflect Nextcloud 29.
=> Update README.md to Nextcloud 29

snap/snapcraft.yaml
=> Update PHP to 8.2.20

CHANGELOG, README.md, snap/snapcraft.yaml
Fix #2724 
Fix #2738 
Fix #2767
Fix #2769
=> Release 29.0.2snap1

src/apache/conf/httpd.conf
We weren't compressing JS files because of this.
=> httpd.conf: update javascript MIME types to compress

snap/snapcraft.yaml
=> Update Nextcloud to 29.0.3

snap/snapcraft.yaml
=> Update MySQL to 8.0.38

snap/snapcraft.yaml
=> apache: upgrade to 2.4.60

snap/snapcraft.yaml
=> Update Apache to 2.4.61

snap/snapcraft.yaml
=> Upgrade Apache to 2.4.62

snap/snapcraft.yaml
=> nextcloud: update to 27.1.11

snap/snapcraft.yaml
=> Update Nextcloud to 29.0.4

snap/snapcraft.yaml
=> Update MySQL to 8.0.39

snap/snapcraft.yaml
=> Upgrade Nextcloud to 29.0.5

snap/snapcraft.yaml
=> Upgrade PHP to 8.2.22

snap/snapcraft.yaml
=> Update Nextcloud to 29.0.6

snap/snapcraft.yaml
=> Update Nextcloud to 29.0.7

src/nextcloud/fixes/existing-install/5_regenerate-assets.sh
As discusses in [#2878](https://github.com/nextcloud-snap/nextcloud-snap/issues/2878#issuecomment-2349036856)
=> nextcloud: include expensive steps on repair

snap/snapcraft.yaml
=> Update PHP to 8.2.24

README.md
as discussed with @pachulo, make PR for adding wiki reference to readme
=> add wiki reference to readme

README.md, snap/snapcraft.yaml, src/redis/config/redis.conf
=> Update Redis to 7.2.6

README.md, snap/snapcraft.yaml, src/redis/config/redis.conf
Also:
- update PHPRedis to 6.1.0
- update redis.conf
- set locale-collate to "C"
- update README with current redis minor version
=> redis: update to 7.2.6

src/nextcloud/fixes/existing-install/8_flush_redis_db.sh
=> nextcloud-fixer: flush redis DB

snap/snapcraft.yaml
=> Update MySQL to 8.0.40

snap/snapcraft.yaml
=> don't ignore `.reuse`

snap/snapcraft.yaml
=> Update Nextcloud to 30.0.1

snap/snapcraft.yaml
=> Update Nextcloud to 30.0.2

.github/dependabot.yml
I think this is worth it, what do you think @kyrofa ?
=> Enable Dependabot version update for actions

.github/workflows/launchpad.yml
This should fix the problem we have with Launchpad just getting lightweight tags from the action. More context [here](https://github.com/nextcloud-snap/nextcloud-snap/issues/2966#issuecomment-2502193356).
=> actions: fix launchpad getting lightweight tags

snap/snapcraft.yaml
=> Update Nextcloud 30.0.3

snap/snapcraft.yaml
=> Update Nextcloud to 30.0.4

src/apache/utilities/apache-utilities, src/mysql/support-files/mysql.server
=> Double Quoting in SRC Scripts

.github/spawn-dailies.sh, .github/workflows/test-daily.yml
=> tests: remove v28 dailies

README.md
edit reference to cron, change value 15 minutes to default 5 minutes
=> README: Fix the default time lapse between cron.php runs

snap/snapcraft.yaml
=> Upgrade Nextcloud to 30.0.5

snap/snapcraft.yaml, src/php/config/php-fpm.conf, src/php/config/php-fpm.d/www.conf, src/php/config/php.ini, tests/integration/change_mode_spec.rb
=> PHP: update to 8.3.14

snap/snapcraft.yaml
=> nextcloud: update to 28.0.14

snap/snapcraft.yaml
=> Update MySQL to 8.0.41

snap/snapcraft.yaml
=> Update Apache to 2.4.63

snap/snapcraft.yaml
=> Update Nextcloud to 30.0.6

snap/snapcraft.yaml
=> Upgrade PHP to 8.3.17

snap/snapcraft.yaml
=> Update PHP to 8.3.17

.github/workflows/test.yml
Let's see if everything works OK after updating the image to 22.04 🤞
=> actions: update ubuntu image for integration test

tests/integration/change_php_memory_limit_spec.rb, tests/integration/enable_https_spec.rb, tests/integration/import_export_spec.rb, tests/integration/login_spec.rb
The commit is from a date when our tests were passing. Let's see if we are lucky.
=> tests: workaround intermitent failing of integration tests

snap/snapcraft.yaml
=> Upgrade PHP to 8.3.19

snap/snapcraft.yaml
=> nextcloud: update to 30.0.7

snap/snapcraft.yaml
=> nextcloud: update to 29.0.14

src/nextcloud/fixes/existing-install/maintenance/2_fix-row-format.sh
Also print progress for logging purposes-- this takes a while.
=> fixer: actually fix row format

snap/snapcraft.yaml
=> Update Nextcloud to 31.0.3

CHANGELOG, src/nextcloud/fixes/existing-install/maintenance/2_fix-row-format.sh
- fixer: actually fix row format
=> Release 31.0.2snap2

snap/snapcraft.yaml
=> Update MySQL to 8.0.42

snap/snapcraft.yaml
=> Update Nextcloud to 31.0.4

snap/snapcraft.yaml
=> nextcloud: update to 30.0.10

snap/snapcraft.yaml
=> Update Nextcloud to 31.0.5

snap/snapcraft.yaml
=> nextcloud: update to 30.0.11

snap/snapcraft.yaml
=> Update Nextcloud to 31.0.6

snap/snapcraft.yaml
=> Update Redis to 7.2.10

snap/snapcraft.yaml
=> Update Apache to 2.4.64

snap/snapcraft.yaml
=> Update MySQL to 8.0.43

snap/snapcraft.yaml
=> Update Apache to 2.4.65

snap/snapcraft.yaml
=> Update Nextcloud to 31.0.8

snap/snapcraft.yaml
=> Update Redis to 7.2.11
